/* ============================================================
 *  Rechtsgrundlagen & Vertragsrecht – Altfragen
 * ============================================================ */

SUBJECTS.push({
  name: "Rechtsgrundlagen & Vertragsrecht",
  icon: "⚖️",
  description: "Altfragen aus der VO Rechtsgrundlagen & Vertragsrecht.",

  kk: [
    {id:1, category:"Verzug", question:"Verzug stellt ein dauerhaftes Leistungshindernis dar.", answer:"✗ Falsch\\n\\neine bloß vorübergehende, aber behebbare Leistungsstörung"},
    {id:2, category:"Stellvertretung & Vollmacht", question:"Die Vollmacht ist hinsichtlich ihres Umfanges notwendigerweise stets gleich wie das Innenverhältnis zwischen Geschäftsherren und Vertreter ausgestaltet.", answer:"✗ Falsch Prokuristen können nach außen mehr als nach innen"},
    {id:3, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel ziehen stets Gesamtnichtigkeit eines Rechtsgeschäfts nach sich", answer:"✗ Falsch\\n\\nEs gibt 3 Möglichkeiten: absolute Nichtigkeit, relative Nichtigkeit & Anfechtbarkeit"},
    {id:4, category:"Schadenersatz", question:"Unter Adäquanzprinzip versteht man den Grundsatz, dass ohne Verschulden kein Schadensersatz geleistet werden muss.", answer:"✗ Falsch\\n\\nDas Adäquanzprinzip besagt, dass ein Schaden nur dann ersetzt werden muss, wenn er eine adäquate (vorhersehbare) Folge einer Handlung ist. Ohne Verschulden kein Schadensersatz = Verschuldensprinzip"},
    {id:5, category:"Verjährung", question:"Tritt Verjährung ein, geht zwar die Klagbarkeit verloren, nicht jedoch das Recht an sich", answer:"✓ Richtig\\n\\nVerjährung §1478 ABGB bedeutet, dass ein Anspruch nicht mehr gerichtlich durchgesetzt werden kann"},
    {id:6, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Leihvertrag ist ein Realvertrag", answer:"✓ Richtig"},
    {id:7, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Verwahrungsvertrag ist ein Realvertrag", answer:"✓ Richtig"},
    {id:8, category:"Kaufvertrag & Eigentumsübertragung", question:"Ein Kaufvertrag über eine Liegenschaft ist ein Realvertrag.", answer:"✗ Falsch\\n\\nKonsensualvertrag"},
    {id:9, category:"Gewährleistung", question:"Preisminderung und Wandlung werden als primäre Gewährleistungsbehelfe bezeichnet", answer:"✗ Falsch\\n\\nPrimär = Verbesserung & Austausch"},
    {id:10, category:"Allgemeines Vertragsrecht", question:"Ein 15- Jähriger darf über alle ihm überlassenen Gegenstände unumschränkt verfügen.", answer:"✗ Falsch"},
    {id:11, category:"Wurzelmängel & Nichtigkeit", question:"Die Laesio enormis ist den Wurzelmängel zuzurechnen.", answer:"✓ Richtig\\n\\nbetrifft die Vertragsgrundlage (Preis), daher zählt sie zu den Wurzelmängel"},
    {id:12, category:"Wurzelmängel & Nichtigkeit", question:"Laesio enormis liegt bei einem Wertverhältnis von 50:100 vor.", answer:"✗ Falsch\\n\\nLeasio enormis liegt vor, wenn der Käufer weniger als die Hälfte des wahren Wertes bezahlt. Wenn das Wertverhältnis genau 50:100 ist, wurde genau die Hälfte gezahlt à Laesio enormis greift hier nicht. Wertverhältnis müsste schlechter sein als 50:100 (z.B. 40:100 oder 30:100"},
    {id:13, category:"Allgemeines Vertragsrecht", question:"Als Anerkenntnis bezeichnet man einen Vertrag, mit dem Streitpunkte in einem Vertragsverhältnis dadurch ausgeräumt werden, dass ein Partner (nicht beide) nachgibt.", answer:"✓ Richtig\\n\\neine einseitige Erklärung, mit der eine Partei eine Schuld oder ein Recht bestätigt"},
    {id:14, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — liegt nur bei Streitigkeiten zwischen internationalen Organisationen vor.", answer:"✗ Falsch\\n\\nnicht nur internationale Organisationen"},
    {id:15, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — liegt immer dann vor, wenn Berührungspunkte zu mehr als einen Staat bestehen.", answer:"✓ Richtig\\n\\n… kann niemals vorliegen, wenn die Streitparteien im selben Staat wohnen."},
    {id:16, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — kann niemals vorliegen, wenn die Streitparteien im selben Staat wohnen.", answer:"✗ Falsch\\n\\n… wird stets nach internationalem Einsichtsrecht beurteilt."},
    {id:17, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — wird stets nach internationalem Einsichtsrecht beurteilt.", answer:"✗ Falsch\\n\\nnach unterschiedlichen Rechtsformen"},
    {id:18, category:"Forderungsabtretung", question:"Anders als ein bloßer Gläubigerwechsel (Zession) oder ein bloßer Schuldnerwechsel (Schuldübernahme) ist die Übertragung einer Vertragsposition als Ganzes (Vertragsübernahme) nicht möglich (und aus diesem Grund nirgendwo gesetzlich geregelt).", answer:"✗ Falsch\\n\\nVertragsübernahmen sind in der Praxis möglich und üblich, insbesondere Miet- oder Geschäftsverträge benötigen aber Zustimmung aller Beteiligten"},
    {id:19, category:"Kaufvertrag & Eigentumsübertragung", question:"Die Eigentumseinverleibung im Grundbuch hat grundsätzlich konstruktive Wirkung.", answer:"✓ Richtig\\n\\ndie Eintragung ist nicht nur eine Bestätigung (deklarativ), sondern begründet das Eigentum (konstitutiv)"},
    {id:20, category:"Allgemeines Vertragsrecht", question:"Die Vereinbarung eines Kündigungsverzeichnis für eine vorweg begrenzte Zeit.", answer:"✗ Falsch\\n\\nVerstößt NICHT gegen die guten Sitten"},
    {id:21, category:"Sittenwidrigkeit", question:"Eine Vereinbarung, wonach sich ein Einzelhändler verpflichtet, sein gesamtes Warensortiment ausschließlich bei einem bestimmten Großhändler zu beziehen.", answer:"✓ Richtig\\n\\nverstoßt gegen die guten Sitten"},
    {id:22, category:"Geschäftsfähigkeit", question:"Die Geschäftsfähigkeit beginnt mit der Lebendgeburt und endet mit dem Tod", answer:"✓ Richtig"},
    {id:23, category:"Eigentum & Besitz", question:"Welche der folgenden Aussagen trifft/treffen auf den gutgläubigen Erwerb gemäß §367 ABGB zu: Es muss ein entgeltliches Titelgeschäft vorliegen", answer:"✓ Richtig"},
    {id:24, category:"Allgemeines Vertragsrecht", question:"Gutgläubiger Erwerb §367 ABGB — Es muss um den Erwerb einer unbeweglichen, körperlichen Sache gehen.", answer:"✗ Falsch\\n\\nNur bewegliche & körperliche Sachen (nicht unbewegliche)"},
    {id:25, category:"Allgemeines Vertragsrecht", question:"Gutgläubiger Erwerb §367 ABGB — Der Veräußerer muss hinsichtlich seiner Eigentümerstellung redlich sein.", answer:"✓ Richtig"},
    {id:26, category:"Allgemeines Vertragsrecht", question:"Gutgläubiger Erwerb §367 ABGB — Der Veräußerer muss entweder UN sein oder Vertrauensmann des vorigen Eigentümers, oder der Erwerb muss im Rahmen einer öffentlichen Versteigung stattfinden.", answer:"✓ Richtig"},
    {id:27, category:"Kaufvertrag & Eigentumsübertragung", question:"Gutgläubiger Erwerb §367 ABGB — Es muss eine Übergabe (Modus) erfolgen.", answer:"✓ Richtig"},
    {id:28, category:"Forderungsabtretung", question:"Eine Forderungsabtretung (Zession) ist ein Verfügungsgeschäft", answer:"✓ Richtig"},
    {id:29, category:"Irrtum & Täuschung", question:"Wenn ein Vertrag nach Erbringung einer Leistung (etwa wegen Irrtums) aufgelöst wird, kann die erbrachte Leistung bereicherungsrechtlich zurückgefordert werden.", answer:"✓ Richtig\\n\\nwenn ein Vertrag nach Leistungserbringung aufgelöst wird, kann die Leistung bereicherungsrechtlich zurückgefordert werden, sowohl für Geldzahlungen als auch Sachleistungen"},
    {id:30, category:"Allgemeines Vertragsrecht", question:"Das Vertragsverhältnis ist beendet, wenn alle Verbindlichkeiten erfüllt wurden.", answer:"✓ Richtig\\n\\n, Ausnahme gibt es für nachträgliche Verpflichtungen wie Gewährleistung oder Schadensersatz"},
    {id:31, category:"Stellvertretung & Vollmacht", question:"Bei einer wirksamen Stellvertretung kommt das Rechtsgeschäft des Dritten unmittelbar mit dem Vertretenen zustande.", answer:"✓ Richtig"},
    {id:32, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Erklärungen unter Freunden", answer:"✗ Falsch"},
    {id:33, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Erklärungen im Familienkreis", answer:"✗ Falsch"},
    {id:34, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Zeitungsinseraten", answer:"✓ Richtig"},
    {id:35, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Erklärungen am Telefon", answer:"✗ Falsch"},
    {id:36, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Scherzerklärungen", answer:"✓ Richtig"},
    {id:37, category:"Gewährleistung", question:"Ist ein Mangel geringfügig, kann ein Wandlungsbegehren keinen Erfolg haben.", answer:"✓ Richtig\\n\\nein Wandlungsbegehren ist nur möglich, wenn der Mangel nicht geringfügig ist. Bei einem geringfügigen Mangel kann nur Preisminderung verlangt werden §392 Abs 4 ABGB"},
    {id:38, category:"Verjährung", question:"Für die Anfechtung des Rechtsgeschäfts wegen Irrtums gilt eine Verjährungsfrist von drei Jahren ab Kenntnis des Irrtums.", answer:"✗ Falsch\\n\\nab Vertragsabschluss"},
    {id:39, category:"Gewährleistung", question:"Eine Konkurrenz ist denkbar… … zwischen Gewährleistungsbehelfen und Irrtumsanfechtung", answer:"✓ Richtig"},
    {id:40, category:"Gewährleistung", question:"Eine Konkurrenz ist denkbar — zwischen Gewährleistungsbehelfen und Nichterfüllungsbehelfen", answer:"✗ Falsch"},
    {id:41, category:"Wurzelmängel & Nichtigkeit", question:"Eine Konkurrenz ist denkbar — zwischen Irrtumsanfechtung und laesio enormis", answer:"✓ Richtig"},
    {id:42, category:"Irrtum & Täuschung", question:"Eine Konkurrenz ist denkbar — zwischen Nichterfüllungsbehelfen und Irrtumsanfechtung", answer:"✓ Richtig"},
    {id:43, category:"Schadenersatz", question:"Eine Konkurrenz ist denkbar — zwischen Schadenersatzansprüchen und Gewährleistungsbehelfen", answer:"✓ Richtig"},
    {id:44, category:"Kaufvertrag & Eigentumsübertragung", question:"Konsumenten können von einem Kaufvertrag binnen 2 Wochen unter Vorlage der Rechnung zurücktreten (allgemeines Rücktrittsrecht nach KSchG)", answer:"✗ Falsch\\n\\nman könnte binnen 14 Tagen zurücktreten, wenn man im Online-Shop eine Sache erworben hat bzw. außerhalb der Geschäftsräume - § 3 KSchG"},
    {id:45, category:"Verzug", question:"Gerät der Schuldner in Teilverzug, kann der Gläubiger bei Unteilbarkeit der Leistung vom gesamten Vertrag zurücktreten.", answer:"✓ Richtig"},
    {id:46, category:"Vertragsabschluss", question:"Verträge kommen durch Angebot und Nachfrage zustande", answer:"✗ Falsch\\n\\nAngebot – Offerte & Annahme - Akzeptanz"},
    {id:47, category:"Konsumentenschutz", question:"Im Konsument Schutzgesetz sind einige spezielle Rücktrittsrechte geregelt.", answer:"✓ Richtig"},
    {id:48, category:"Internationales Privatrecht", question:"Wenn die beteiligten Personen dieselbe Staatsbürgerschaft haben, liegt sicher kein Sachverhalt mit Auslandberührung vor.", answer:"✗ Falsch\\n\\nVertrag wird im Ausland geschlossen, Erfüllungsort liegt im Ausland"},
    {id:49, category:"Vertragsabschluss", question:"Wer in der Zeitung sein Auto zum Verkauf inseriert, macht ein Verbindliches Angebot.", answer:"✗ Falsch\\n\\nAnzeige in Zeitung ist meist nur ein invitatio ad offerendum"},
    {id:50, category:"Eigentum & Besitz", question:"Der Dieb einer Sache hat die Rechtsstellung eines Besitzers, da er mit der gestohlenen Sache verfährt, als wäre sie seine eigene (z.B. veräußert er sie)", answer:"✗ Falsch"},
    {id:51, category:"Internationales Privatrecht", question:"Österreich hat mit dem IPRG (Internationales Privatrecht) ein Autonomes Koalitionsrecht", answer:"✓ Richtig\\n\\nIPRG bestimmt, welches Recht auf internationale Verträge, Schadenersatzfälle usw. angewendet wird"},
    {id:52, category:"Irrtum & Täuschung", question:"Die Möglichkeit zur Anfechtung eines Vertrags wegen Irrtums verjährt binnen 3 Jahren ab Vertragserfüllung.", answer:"✗ Falsch\\n\\nab Vertragsabschluss!"},
    {id:53, category:"Wurzelmängel & Nichtigkeit", question:"Ein Wurzelmangel setzt stets einen gültig zustande gekommen Vertrag voraus.", answer:"✗ Falsch\\n\\nWurzelmangel = Fehler beim Entstehen des Vertrags"},
    {id:54, category:"Konsumentenschutz", question:"Das Transparenzgebot gilt für alle vertraglichen Vereinbarungen zwischen Unternehmen und Verbrauchern.", answer:"✗ Falsch\\n\\nTransparenzgebot gilt nur für AGB im Verbraucherrecht"},
    {id:55, category:"Gewährleistung", question:"Eine Leistung ist mangelhaft, wenn gewöhnlich vorausgesetzte Eigenschaften fehlen", answer:"✓ Richtig\\n\\nGewöhnlich vorausgesetzte Eigenschaften sind jene, die eine Sache haben muss, damit sie für ihren üblichen Zweck geeignet ist."},
    {id:56, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Legalzession", answer:"✓ Richtig"},
    {id:57, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einem Schuldbeitritt (ein zusätzlicher Schuldner tritt hinzu, kein Gläubigerwechsel)", answer:"✗ Falsch"},
    {id:58, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Sicherungsabtretung", answer:"✓ Richtig"},
    {id:59, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Mantelzession", answer:"✓ Richtig"},
    {id:60, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Novation (alte Schuld wird durch neue ersetzt)", answer:"✗ Falsch"},
    {id:61, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen: Die Dienstbarkeit", answer:"✓ Richtig"},
    {id:62, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen — Die Reallast", answer:"✓ Richtig"},
    {id:63, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen — Die Dienstleistung", answer:"✗ Falsch\\n\\nDienstleistung ist kein dingliches Recht"},
    {id:64, category:"Eigentum & Besitz", question:"Zu den dinglichen Rechten zählen — Der Besitz", answer:"✗ Falsch\\n\\nBesitz ist kein dingliches Recht (nur faktische Herrschaft)"},
    {id:65, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen — Das Baurecht", answer:"✓ Richtig"},
    {id:66, category:"Allgemeines Vertragsrecht", question:"Die Volljährigkeit erreicht man mit dem 19. Geburtstag", answer:"✗ Falsch"},
    {id:67, category:"Eigentum & Besitz", question:"Miteigentum kann nur aus ohne Wertverlust real teilbaren Sachen bestehen.", answer:"✗ Falsch\\n\\nMiteigentum kann auch an unteilbare Sachen bestehen (Grundstück, Kunstwerk)"},
    {id:68, category:"Allgemeines Vertragsrecht", question:"Was ist Voraussetzung für das wirksame Zustandekommen eines Vertrags? Die Parteien müssen sich einig sein", answer:"✓ Richtig\\n\\nEs darf kein Motivirrtum vorliegen"},
    {id:69, category:"Irrtum & Täuschung", question:"Es darf kein Motivirrtum vorliegen", answer:"✗ Falsch\\n\\nDer Inhalt des Vertrags darf nicht rechtlich unmöglich sein"},
    {id:70, category:"Allgemeines Vertragsrecht", question:"Der Inhalt des Vertrags darf nicht rechtlich unmöglich sein", answer:"✓ Richtig\\n\\nDie Erklärungen der Parteien müssen ernst gemeint sein"},
    {id:71, category:"Allgemeines Vertragsrecht", question:"Die Erklärungen der Parteien müssen ernst gemeint sein", answer:"✓ Richtig\\n\\nDer Vertrag muss vor Zeugen geschlossen werden"},
    {id:72, category:"Allgemeines Vertragsrecht", question:"Der Vertrag muss vor Zeugen geschlossen werden", answer:"✗ Falsch"},
    {id:73, category:"Allgemeines Vertragsrecht", question:"Ein berühmtes Beispiel für den Wegfall der Geschäftsgrundlagen ist der „Krönungszug“ Fall", answer:"✓ Richtig"},
    {id:74, category:"Sittenwidrigkeit", question:"Der OGH definiert „Verletzung der guten Sitten“ als Gefährdung anerkannter Ordnungen, Freiheitsbeschränkungen, Ausnutzung einer Übermachtposition, schwere Äquivalenzstörungen oder Manifestation einer verwerflichen Gesinnung.", answer:"✓ Richtig\\n\\nVerletzung der guten Sitten bezieht sich auf unangemessene Ausnutzung von Macht, Ungleichgewicht oder moralische Verwerflichkeit § 879 ABGB"},
    {id:75, category:"Verzug", question:"Bei objektivem Verzug — kann der Gläubiger auf Erfüllung beharren", answer:"✓ Richtig"},
    {id:76, category:"Verzug", question:"Bei objektivem Verzug — kann der Gläubiger unter Setzung einer angemessenen Nachfrist vom Vertrag zurücktreten", answer:"✓ Richtig"},
    {id:77, category:"Verzug", question:"Bei objektivem Verzug — wird der Vertrag ex lege aufgelöst", answer:"✗ Falsch"},
    {id:78, category:"Verzug", question:"Bei objektivem Verzug — liegt ein Verschulden des Schuldners vor", answer:"✗ Falsch\\n\\nBei objektivem Verzug liegt kein Verschulden vor (objektive Fristversäumnis)"},
    {id:79, category:"Verzug", question:"Bei objektivem Verzug — gelten §§ 922 ff ABGB", answer:"✗ Falsch\\n\\n§918 und §921 ABGB"},
    {id:80, category:"Allgemeines Vertragsrecht", question:"Wenn der Käufer die Kaufsache bei Fälligkeit nicht wie vereinbart abholt und sie danach beim Verkäufer gestohlen wird, steht dem Verkäufer dennoch der Kaufpreis zu.", answer:"✓ Richtig\\n\\nAb Annahmeverzug trägt Käufer die Gefahr"},
    {id:81, category:"Kaufvertrag & Eigentumsübertragung", question:"Beim Erwerb einer Liegenschaft, z.B. einer Wohnung, erwirbt man das Eigentum durch Schlüsselübergabe. Die Eintragung im Grundbuch ist zwar ratsam, aber nicht unbedingt notwendig.", answer:"✗ Falsch\\n\\nEintragung ist notwendig"},
    {id:82, category:"Wurzelmängel & Nichtigkeit", question:"Wer aufgrund eines nichtigen Vertrages eine Leistung erbringt, ist selbst schuld und kann diese Leistung nicht zurückfordern.", answer:"✗ Falsch\\n\\nkann zurückgefordert werden"},
    {id:83, category:"Gewährleistung", question:"Beim Kauf in Pausch und Bogen kann der Übernehmer im Fall mangelhafter Leistung zwar Verbesserung iwS und Preisminderung begehren eine Wandlung kommt hingegen nicht in Frage", answer:"✓ Richtig"},
    {id:84, category:"Gewährleistung", question:"Eine Leistung ist mangelhaft, wenn gewöhnlich vorausgesetzte Eigenschaften fehlen.", answer:"✓ Richtig"},
    {id:85, category:"Forderungsabtretung", question:"Wird der Schuldner von der Zession verständigt, kann er trotzdem weiterhin schuldbefreiend an dem Altgläubiger leisten.", answer:"✗ Falsch\\n\\nNach Verständigung von der Zession muss der Schuldner an den neuen Gläubiger (Zessionar) leisten"},
    {id:86, category:"Eigentum & Besitz", question:"Ein Eigentumsvorbehalt… … bewirkt, dass der Eigentumübergang auflösend befristet ist.", answer:"✗ Falsch\\n\\nEigentumsvorbehalt = aufschiebend bedingt (Eigentum geht erst bei Zahlung über), nicht auflösend befristet"},
    {id:87, category:"Allgemeines Vertragsrecht", question:"Ein Eigentumsvorbehalt — verschafft dem Veräußerer in der Insolvenz des Erwerbers ein Aussonderungsrecht", answer:"✓ Richtig"},
    {id:88, category:"Allgemeines Vertragsrecht", question:"Ein Eigentumsvorbehalt — ergibt sich bei Kreditkäufen schon aus zwingenden gesetzlichen Vorschriften", answer:"✗ Falsch\\n\\nmuss vertraglich vereinbart werden"},
    {id:89, category:"Eigentum & Besitz", question:"Ein Eigentumsvorbehalt — lässt das Eigentum erst bei vollständiger Zahlung des vertraglich vereinbarten Entgelts übergehen", answer:"✓ Richtig"},
    {id:90, category:"Allgemeines Vertragsrecht", question:"Ein Eigentumsvorbehalt — ermöglicht es dem Veräußerer grundsätzlich, die veräußerte Sache im Fall der Nichtzahlung des Entgelts auch von einem Dritten herauszuverlangen.", answer:"✓ Richtig"},
    {id:91, category:"Allgemeines Vertragsrecht", question:"Bei Fälligkeit der Sachleistung trägt in der Regel der Sachgläubiger die Preisgefahr. Wird der Leistungsgegenstand zerstört, muss der Sachgläubiger dennoch den Preis bezahlen.", answer:"✗ Falsch\\n\\nDie Preisgefahr geht nicht bei Fälligkeit über – bis zur Übergabe trägt Verkäufer die Preisgefahr à Käufer haftetet erst wenn er das Ding schon übernommen hat oder er in Annahmeverzug ist"},
    {id:92, category:"Allgemeines Vertragsrecht", question:"Die Erfüllung einer Gattungsschuld kann niemals unmöglich werden.", answer:"✗ Falsch\\n\\nkann aber unmöglich sein, wenn z.B. die ganze Ernte von 2025 versprochen worden ist und die gesamte Ernte abbrennt"},
    {id:93, category:"Allgemeines Vertragsrecht", question:"Die Erfüllung einer Gattungsschuld kann unmöglich werden.", answer:"✓ Richtig"},
    {id:94, category:"Schadenersatz", question:"Trifft den Schuldner (erstellt Leistung) am Unmöglich-Werden einer Leistung ein Verschulden, kann der Gläubiger (fragt nach Leistung) Schadenersatz verlangen.", answer:"✓ Richtig"},
    {id:95, category:"Wurzelmängel & Nichtigkeit", question:"Verträge, bei denen die öffentlichen Interessen (Drogenhandel) gegen die Gültigkeit sprechen, sind absolut nichtig.", answer:"✓ Richtig\\n\\nVerträge nach § 879 ABGB sind absolut nichtig. z.B.: Ein Vertrag der gegen öffentliche Ordnung oder gute Sitten verstößt"},
    {id:96, category:"Allgemeines Vertragsrecht", question:"Nach Vertragsabschluss können Veränderungen des Vertragsinhalt nicht einseitig vorgenommen werden", answer:"✓ Richtig\\n\\nnur beidseitig"},
    {id:97, category:"Verzug", question:"Bei Gläubigerverzug (Annahmeverzug) haftet der Schuldner nur noch für grobes Verschulden.", answer:"✓ Richtig\\n\\nSchuldner haftet jetzt nur mehr für Vorsatz oder grobe Fahrlässigkeit"},
    {id:98, category:"Allgemeines Vertragsrecht", question:"Juristische Personen handeln durch ihre Organe", answer:"✓ Richtig"},
    {id:99, category:"Stellvertretung & Vollmacht", question:"Ein sogenannter „Mittelbarer Stellvertreter“ handelt im eigenen Namen, aber auf fremde Rechnung", answer:"✓ Richtig"},
    {id:100, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — mehrdeutig ist", answer:"✓ Richtig"},
    {id:101, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — unvollständig ist", answer:"✓ Richtig"},
    {id:102, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — unverständlich ist", answer:"✓ Richtig"},
    {id:103, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — faktisch unmöglich", answer:"✗ Falsch\\n\\nfaktische Unmöglichkeit führt nicht zu Dissens"},
    {id:104, category:"Sittenwidrigkeit", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — sittenwidrig ist", answer:"✗ Falsch"},
    {id:105, category:"Wurzelmängel & Nichtigkeit", question:"Absolute Nichtigkeit kann von jedermann geltend gemacht werden.", answer:"✓ Richtig"},
    {id:106, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — Scherzerklärungen", answer:"✓ Richtig"},
    {id:107, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — Werbeaussagen", answer:"✓ Richtig"},
    {id:108, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — sogenannten Bühnenerklärungen", answer:"✓ Richtig"},
    {id:109, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — Lehrveranstaltungen", answer:"✓ Richtig"},
    {id:110, category:"Allgemeines Vertragsrecht", question:"Geldschulden sind im Zweifel durch Giroüberweisungen zu bezahlen", answer:"✗ Falsch\\n\\nGeldschulden sind Bringschulden, immer in bar außer es wurde vereinbart, dass die Überweisung auch gilt"},
    {id:111, category:"Eigentum & Besitz", question:"Die Ersitzung ist eine Form des originärem Eigentumserwerb", answer:"✓ Richtig"},
    {id:112, category:"Allgemeines Vertragsrecht", question:"Ob ein Rechtsgeschäft bei einem Gesetzesverbot iSd § 879 ABGB richtig ist, ergibt sich aus dem Schutzzweck der verletzten Norm.", answer:"✓ Richtig"},
    {id:113, category:"Eigentum & Besitz", question:"Ein Schenkungsversprechen ohne Übergabe bedarf zu seiner Gültigkeit eines Notariatsakt.", answer:"✓ Richtig"},
    {id:114, category:"Verzug", question:"Die gesetzlichen Verzugszinsen betragen nach dem ABGB 4%.", answer:"✓ Richtig"},
    {id:115, category:"Schadenersatz", question:"Schadensersatz ist im Allgemeinen dann zu leisten, wenn man rechtswidrig und schuldhaft einen Schaden verursacht.", answer:"✓ Richtig"},
    {id:116, category:"Gewährleistung", question:"Eine Konkurrenz zwischen Nichterfüllungs- und Gewährleistungsbehelfen ist ausgeschlossen", answer:"✓ Richtig"},
    {id:117, category:"Gewährleistung", question:"Die Gewährleistungspflicht kann grundsätzlich von den Vertragsparteien durch entsprechende vertragliche Vereinbarung verlängert oder verkürzt werden", answer:"✓ Richtig"},
    {id:118, category:"Schadenersatz", question:"Nicht jeder zugefügte Schaden ist ersatzfähig", answer:"✓ Richtig"},
    {id:119, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel zieht stets die Gesamtnichtigkeit eines Rechtsgeschäfts nach sich", answer:"✗ Falsch"},
    {id:120, category:"Verzug", question:"Bei Gläubigerverzug haftet der Schuldner nur noch grobes Verschulden.", answer:"✓ Richtig"},
    {id:121, category:"Forderungsabtretung", question:"Eine Forderungsabtretung bedarf eines Rechtsgrundes, um wirksam zu sein. Als Rechtsgrund kommt etwa ein Factoring-Vertrag in Frage.", answer:"✓ Richtig\\n\\nRechtsgründe: Kaufvertrag, Schenkung, Sicherungsvereinbarung, Factoring-Vertrag. Factoring = ein UN verkauft seine Forderungen an eine Factoring-Gesellschaft"},
    {id:122, category:"Allgemeines Vertragsrecht", question:"Bei Kreditkauf trägt das Insolvenzrisiko der Käufer.", answer:"✗ Falsch\\n\\nder Verkäufer trägt es!"},
    {id:123, category:"Allgemeines Vertragsrecht", question:"Ein Baby ist rechtsfähig und kann daher z.B. Eigentümer eines großen Hauses sein", answer:"✓ Richtig"},
    {id:124, category:"Allgemeines Vertragsrecht", question:"Bei Spezialschuld trägt der Sachschuldner die Leistungsgefahr", answer:"✓ Richtig\\n\\nbei Spezialschulden trägt der Schuldner die Leistungsgefahr, weil die Ware einzigartig und nicht ersetzt werden kann. Spezialschuld = liegt vor, wenn eine ganz bestimmte individuelle Sache geschuldet wird"},
    {id:125, category:"Gewährleistung", question:"Ziel der Gewährleistung ist die Herstellung von subjektiver Äquivalenz.", answer:"✓ Richtig\\n\\nSubjektive Äquivalenz = die Leistung soll genau das haben, was die Parteien konkret vereinbart haben"},
    {id:126, category:"Kaufvertrag & Eigentumsübertragung", question:"Anders als nach ABGB kommt im UN-Kaufrecht ein Kaufvertrag grundsätzlich nicht durch Konsens, sondern durch Warensendung zustande", answer:"✗ Falsch\\n\\nKonsens = Angebot & Annahme) (es kommt durch Konsens zustande, nur in Ausnahmefällen durch Warensendung"},
    {id:127, category:"Verzug", question:"Die Rechte auf Gewährleistung können grundsätzlich neben jenen wegen Verzugs geltend gemacht werden.", answer:"✗ Falsch\\n\\nGewährleistung erst ab Übergabe, bei Verzug ist noch keien Übergabe erfolgt"},
    {id:128, category:"Allgemeines Vertragsrecht", question:"Der Widerruf einer Schenkung ist ausnahmslos ausgeschlossen", answer:"✗ Falsch\\n\\nbei Motivirrtum ist Schenkung beachtlich"},
    {id:129, category:"Gewährleistung", question:"Die Rechte aus Gewährleistung können grundsätzlich neben jenen aus Irrtum geltend gemacht werden.", answer:"✓ Richtig\\n\\nweil sie unterschiedliche Ziele verfolgen"},
    {id:130, category:"Konsumentenschutz", question:"Das KSchG enthält typischerweise relativ zwingende Normen", answer:"✓ Richtig\\n\\ndarf nur Zugunsten des Verbrauchers abweichen"},
    {id:131, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Darlehensvertrag ist ein Realvertrag", answer:"✗ Falsch"},
    {id:132, category:"Allgemeines Vertragsrecht", question:"Wird aufgrund eines bereits erfüllten Vertrages irrtümlich nochmals geleistet, steht dem Leistenden eine Leistungskondition offen.", answer:"✓ Richtig\\n\\nLeistungskondition = irrtümlich/doppelt bezahlt"},
    {id:133, category:"Schadenersatz", question:"Adäquanz heißt, dass ohne Verschulden kein Schadenersatz geleistet werden kann.", answer:"✗ Falsch"},
    {id:134, category:"Allgemeines Vertragsrecht", question:"Vorsatz ist eine auffallende und ungewöhnliche Nachlässigkeit", answer:"✗ Falsch\\n\\nVorsatz = bewusstes Handeln | auffallende & ungewöhnliche Nachlässigkeit = Grobe Fahrlässigkeit"},
    {id:135, category:"Gewährleistung", question:"Preisminderung und Wandlung werden als primäre Gewährleistungsbehelfe bezeichnet", answer:"✗ Falsch\\n\\nprimäre Gewährleistungsbehelfe = Verbesserung & Austausch | sekundäre Gewährleistungsbehelfe = Preisminderung & Wandlung"},
    {id:136, category:"Allgemeines Vertragsrecht", question:"Verschuldet der Schuldner die Unmöglichkeit der Leistung und hält der Gläubiger den Vertrag aufrecht so kann er den Differenzanspruch geltend machen", answer:"✗ Falsch\\n\\nrichtig wäre: wenn Vertrag aufrecht bleibt – Ausgleichszahlung | bei Rücktritt von Vertrag – Differenzanspruch"},
    {id:137, category:"Internationales Privatrecht", question:"Bei internationalen Sachverhalten kommt statt des ABGB und des UGB das IPRG zur Anwendung.", answer:"✗ Falsch\\n\\nRichtig: CISG/UNK"},
    {id:138, category:"Allgemeines Vertragsrecht", question:"Beim drittfinanzierten Kauf wird der Kaufpreis dem Käufer nicht vom Verkäufer, sondern von einem mit diesem zusammenarbeitenden Dritten kreditiert.", answer:"✓ Richtig"},
    {id:139, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist in folgenden Fällen beachtlich: — Wenn der Vertrag ohne den Irrtum nicht abgeschlossen worden wäre.", answer:"✗ Falsch"},
    {id:140, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — bei Schenkung", answer:"✓ Richtig"},
    {id:141, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — ... wenn der Motivirrtum listig veranlasst worden ist", answer:"✓ Richtig"},
    {id:142, category:"Konsumentenschutz", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — in Verbraucherverträgen", answer:"✗ Falsch"},
    {id:143, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — wenn das Motiv ausdrücklich zur Bedingung gemacht worden ist", answer:"✓ Richtig"},
    {id:144, category:"Allgemeines Vertragsrecht", question:"Beim Kauf sind die Leistungen grundsätzlich Zug um Zug zu erbringen", answer:"✓ Richtig\\n\\nZug um Zug = Verkäufer muss Sache übergeben, Käufer muss gleichzeitig bezahlen"},
    {id:145, category:"Wurzelmängel & Nichtigkeit", question:"Verträge, bei denen die öffentlichen Interessen gegen die Gültigkeit sprechen, sind absolut nichtig", answer:"✓ Richtig"},
    {id:146, category:"Schadenersatz", question:"Trifft den Schuldner am Unmöglich-werden einer Leistung ein Verschulden, kann der Gläubiger Schadenersatz verlangen", answer:"✓ Richtig"},
    {id:147, category:"Wurzelmängel & Nichtigkeit", question:"Ob ein Rechtsgeschäft bei einem Gesetzesverstoß iSd § 879 ABGB überhaupt in irgendeiner Form nichtig ist, ergibt sich aus dem Schutzzweck der verletzten Norm.", answer:"✓ Richtig"},
    {id:148, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Leihvertrag ist ein Realvertrag", answer:"✓ Richtig"},
    {id:149, category:"Gewährleistung", question:"Ist ein Mangel geringfügig, kann ein Wandlungsbegehren keinen Erfolg haben", answer:"✓ Richtig"},
    {id:150, category:"Irrtum & Täuschung", question:"Irrtum ist unbeachtlich, wenn der Vertrag auch bei Kenntnis der wahren Sachlage, aber mit anderem Inhalt abgeschlossen worden wäre.", answer:"✗ Falsch\\n\\nRichtig wäre es wenn der Irrtum wesentlich und somit beachtlich ist"},
    {id:151, category:"Kaufvertrag & Eigentumsübertragung", question:"Titel und Modus nur beim derivaten nicht aber beim originären Eigentumserwerb gegeben", answer:"✗ Falsch\\n\\nDerivat = Titel & Modus | Originär = nur Modus"},
    {id:152, category:"Konsumentenschutz", question:"Transparenzgebot gilt für Verträge zwischen Unternehmen und Verbraucher.", answer:"✗ Falsch"},
    {id:153, category:"Forderungsabtretung", question:"Forderungsabtretung ist ein Verfügungsgeschäft", answer:"✓ Richtig"},
    {id:154, category:"Allgemeines Vertragsrecht", question:"Verletzt ein Treuhänder seine Pflichten gegenüber dem Treugeber, ist auch der Vertrag mit dem Dritten stets unwirksam.", answer:"✗ Falsch\\n\\nTreuhandverletzung à Haftung im Innenverhältnis | nicht automatisch à Unwirksamkeit im Außenverhältnis"},
    {id:155, category:"Vertragstypen", question:"Ist der Werkvertrag ein Auftrag?", answer:"✗ Falsch"},
    {id:156, category:"Kaufvertrag & Eigentumsübertragung", question:"Zession braucht Modus und Titel", answer:"✓ Richtig"},
    {id:157, category:"Allgemeines Vertragsrecht", question:"Tiere brauchen einen Sachwalter", answer:"✗ Falsch"},
    {id:158, category:"Allgemeines Vertragsrecht", question:"Anerkenntnis ist ein Vertrag, einseitig, unentgeltlicher, gesetzlich nicht geregelter", answer:"✗ Falsch\\n\\nVertrag ist zweiseitig & Anerkenntnis ist nicht zwingend unentgeltlich"},
    {id:159, category:"Allgemeines Vertragsrecht", question:"Wenn im ABGB nicht bestimmt ist, dass der Vertrag anders als schriftlich zu erfolgen hat, muss er schriftlich werden.", answer:"✗ Falsch\\n\\nFormfreiheit"},
    {id:160, category:"Stellvertretung & Vollmacht", question:"Beim Stellvertreter kann es sein, dass er mehr kann als darf", answer:"✓ Richtig"},
    {id:161, category:"Allgemeines Vertragsrecht", question:"Die Fälligkeit der Leistung steht im Gesetz", answer:"✓ Richtig\\n\\n§904 ABGB"},
    {id:162, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: 3 Goldfische", answer:"✓ Richtig"},
    {id:163, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: Ein Wein Jahrgang 1978 der Rebsorte Merlot", answer:"✗ Falsch\\n\\nDas ist Spezialschuld (konkrete Beschreibung)"},
    {id:164, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: Irgendein Bild von Klimt", answer:"✓ Richtig"},
    {id:165, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: Die Mona Lisa", answer:"✗ Falsch\\n\\nDie Mona Lisa ist Spezialschuld (einzigartiges Werk)"},
    {id:166, category:"Kaufvertrag & Eigentumsübertragung", question:"A leiht B sein Rad übers Wochenende. Also ist A in der Zeit Eigentümer des Rades, da Titel und Modus gegen sind.", answer:"✗ Falsch\\n\\nBegründung ist falsch! – A bleibt Eigentümer, weil keine Eigentumsübertragung gewollt ist"},
    {id:167, category:"Irrtum & Täuschung", question:"Ein Kalkulationsirrtum ist ein Geschäftsirrtum", answer:"✗ Falsch\\n\\nMotivirrtum) Geschäftsirrtum = Irrtum über den Inhalt des Geschäfts (z.B. Gegenstand) Motivirrtum = Irrtum über den Beweggrund"},
    {id:168, category:"Sittenwidrigkeit", question:"Ein Verstoß gegen die Sitten sind Freiheitsbeschränkungen, schwere Äquivalenzstörungen, Gefährdung anerkannter Ordnungen, die Ausnutzung einer Übermachtposition.", answer:"✓ Richtig\\n\\nschwere Äquivalenzstörungen = krasses Missverhältnis zwischen Leistung & Gegenleistung"},
    {id:169, category:"Wurzelmängel & Nichtigkeit", question:"Laesio enormis gehört zu den Wurzelmängel.", answer:"✓ Richtig"},
    {id:170, category:"Allgemeines Vertragsrecht", question:"Für einen Bürgen braucht es Zeugen?", answer:"✗ Falsch\\n\\nBürgschaftserklärung muss schriftlich erfolgen"},
    {id:171, category:"Allgemeines Vertragsrecht", question:"Vertragsverhältnis beendet, wenn alle Verbindlichkeiten erfüllt sind?", answer:"✓ Richtig"},
    {id:172, category:"Allgemeines Vertragsrecht", question:"Durch § 972 ABGB, List & Drohung muss nicht aufgehoben werden, kann angepasst werden.", answer:"✗ Falsch\\n\\nRechtsfolge von List & Drohung ist grundsätzlich die Anfechtung des Vertrages und daraus folgt die Aufhebung"},
    {id:173, category:"Gewährleistung", question:"Um Gewährleistung nicht zu verlieren, muss man immer eine Mängelrüge schreiben?", answer:"✗ Falsch"},
    {id:174, category:"Verzug", question:"Konkurrenz zwischen Wurzelmängel und Leistungsstörungen?", answer:"✓ Richtig\\n\\nAnspruchskonkurrenz zwischen Wurzelmängel und Leistungsstörung à wen BEIDES vorliegt kann man selbst wählen, ob man die Gewährleistung geltend macht oder wegen List anfechtet"},
    {id:175, category:"Allgemeines Vertragsrecht", question:"Tausch & Kauf sind zweiseitige Verträge?", answer:"✓ Richtig"},
    {id:176, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel schließen einen gültig zustande gekommen Vertrag aus?", answer:"✗ Falsch"},
    {id:177, category:"Kaufvertrag & Eigentumsübertragung", question:"B borgt Y für eine Woche sein Fahrrad, für diese Zeit wird Y der Eigentümer da Titel und Modus vorliegen.", answer:"✗ Falsch"},
    {id:178, category:"Allgemeines Vertragsrecht", question:"Das Werkunternehmen muss für sein Werk gewährleisten.", answer:"✓ Richtig"},
    {id:179, category:"Stellvertretung & Vollmacht", question:"Da Tiere nicht geschäftsfähig sind bedürfen sie notwendigerweise einen Stellvertreter, wenn sich am rechtsgeschäftlichen Verkehr teilnehmen.", answer:"✗ Falsch"},
    {id:180, category:"Gewährleistung", question:"Der Ausschluss der Gewährleistung beim Privatkauf", answer:"✓ Richtig\\n\\nverstößt NICHT gegen die guten Sitten"},
    {id:181, category:"Allgemeines Vertragsrecht", question:"Als Vergleich bezeichnet man einen Vertrag, mit dem die Vertragspartei Streitpunkte einer bestehenden Rechtsbeziehung durch beidseitiges Nachgeben ausräumen.", answer:"✓ Richtig"},
    {id:182, category:"Internationales Privatrecht", question:"Die Frage welches materielle Recht im Prozess zu einem internationalen Sachverhalt zur Anwendung gelangt, ist eine Frage des internationalen Zivilprozessrechts (IZPR).", answer:"✗ Falsch\\n\\nbetrifft das Internationale Privatrecht (IPR)"},
    {id:183, category:"Allgemeines Vertragsrecht", question:"Was rechtlich unmöglich ist kann nicht Inhalt eines wirksamen Vertrags sein.", answer:"✓ Richtig"},
    {id:184, category:"Allgemeines Vertragsrecht", question:"Neben den allgemeinen Gerichtsstand können auch Wahlgerichtsstände (besondere Gerichtsstände) für die Zuständigkeit eines Gerichts maßgebend sein.", answer:"✓ Richtig"},
    {id:185, category:"Eigentum & Besitz", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — des Käufers", answer:"✗ Falsch"},
    {id:186, category:"Eigentum & Besitz", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — des Verkäufers", answer:"✓ Richtig"},
    {id:187, category:"Eigentum & Besitz", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — eines Dritten der die Sache von dem Käufer erwerben möchte", answer:"✗ Falsch"},
    {id:188, category:"Allgemeines Vertragsrecht", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — eines Kreditinstituts, das dem Käufer den Erwerb ermöglicht", answer:"✗ Falsch"},
    {id:189, category:"Allgemeines Vertragsrecht", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — des Rechtsvorgängers des Verkäufers", answer:"✗ Falsch"},
    {id:190, category:"Allgemeines Vertragsrecht", question:"Verletzt ein Treuhänder seine Pflichten gegenüber dem Treugeben ist auch der Vertrag mit dem Dritten stets unwirksam.", answer:"✗ Falsch\\n\\nVertrag wäre nur unwirksam wenn der Dritte vom Treuverstoß wusste oder bewusst mitgewirkt hat"},
    {id:191, category:"Kaufvertrag & Eigentumsübertragung", question:"Wer eine Liegenschaft von bürgerlichem Eigentum kauft, erwirbt im Allgemeinen selbst dann Eigentum an dieser Liegenschaft, wenn der Grundbuchstand falsch sein sollte. Dies nennt man den Grundbuchrechtlichen Vertrauensschutz.", answer:"✓ Richtig"},
    {id:192, category:"Allgemeines Vertragsrecht", question:"Die Fälligkeit der Leistung steht generell im Gesetz.", answer:"✓ Richtig"},
    {id:193, category:"Allgemeines Vertragsrecht", question:"Eine Auslobung ist ein Vertrag", answer:"✗ Falsch\\n\\nAuslobung = einseitiges Rechtsgeschäft"},
    {id:194, category:"Allgemeines Vertragsrecht", question:"Willenserklärungen müssen den Empfänger zugehen?", answer:"✓ Richtig"},
    {id:195, category:"Allgemeines Vertragsrecht", question:"Willenserklärungen sind anhand des Willens des Erklärenden auszulegen?", answer:"✗ Falsch\\n\\nentscheidend ist das was der Erklärende sagt und nicht was er sich denkt"},
    {id:196, category:"Vertragsabschluss", question:"Bindendes Angebot – A sagt zu B, ich kaufe deinen Fernseher zu einem günstigen Preis und B sagt OK", answer:"✗ Falsch\\n\\nfür ein Bindendes Angebot braucht man die Kaufsache & Kaufpreis"},
    {id:197, category:"Vertragsabschluss", question:"Ein bindendes Angebot liegt NICHT vor bei Geschwistern?", answer:"✗ Falsch"},
    {id:198, category:"Vertragsabschluss", question:"Ein bindendes Angebot liegt vor bei unaufgeforderten Zusendungen?", answer:"✓ Richtig\\n\\ndurch Annahme à"},
    {id:199, category:"Stellvertretung & Vollmacht", question:"Ein Stellvertreter muss keinen eigenen Willen bilden.", answer:"✗ Falsch\\n\\nStellvertreter sollte schon eigenen Willen bilden, Bote sollten keinen eigenen Willen bilden!"},
    {id:200, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel können auch nach Vertragsabschluss eintreten.", answer:"✗ Falsch\\n\\ndanach sind es Leistungsstörungen"},
    {id:201, category:"Eigentum & Besitz", question:"Ein gutgläubiger Erwerb ist nach § 367 ABGB bei einer Schenkung möglich.", answer:"✗ Falsch\\n\\ngutgläubiger Erwerb fordert Entgelt"},
    {id:202, category:"Verzug", question:"Verzugszinsengebühren bei jeder Art von vertraglich geschuldeter Leistung?", answer:"✗ Falsch\\n\\nVerzugszinsen gibt es nur bei Geldschulden"},
    {id:203, category:"Verzug", question:"Wenn der Gläubiger trotz Fälligkeit nicht annimmt, spricht man von Leistungsverzug?", answer:"✗ Falsch\\n\\nsondern Annahmeverzug (Gläubigerverzug). Leistungsverzug = Schuldnerverzug"},
    {id:204, category:"Forderungsabtretung", question:"Ein Schuldnerwechsel liegt vor bei einer Zession?", answer:"✗ Falsch\\n\\nSchuldnerwechsel = Schuldner wechselt | Zession = Gläubiger wechselt"},
    {id:205, category:"Allgemeines Vertragsrecht", question:"Ein Schuldnerwechsel liegt vor bei Anerkenntnis?", answer:"✗ Falsch\\n\\nAnerkenntnis = Schuldner bestätigt das Bestehen einer Schuld"},
    {id:206, category:"Allgemeines Vertragsrecht", question:"Ein Schuldnerwechsel liegt vor bei einer Schuldänderung?", answer:"✗ Falsch\\n\\nSchuldänderung = neue Schuldverhältnis {Novation} – statt Geld liefere ich dir ein Fahrrad à Geldschuld wird durch Sachschuld ersetzt"},
    {id:207, category:"Forderungsabtretung", question:"Ein Schuldnerwechsel liegt vor bei einer Schuldübernahme?", answer:"✓ Richtig"},
    {id:208, category:"Allgemeines Vertragsrecht", question:"Eine verjährte Schuld kann beglichen werden?", answer:"✓ Richtig"},
    {id:209, category:"Allgemeines Vertragsrecht", question:"Ein 15-jähriger darf alleine, d.h. ohne Mitwirkung seiner Eltern, einen Vertrag über einen Ferialjob abschließen.", answer:"✓ Richtig\\n\\ndarf Dienstverträge allein unterzeichnen"},
    {id:210, category:"Allgemeines Vertragsrecht", question:"Eine Schenkung ist kein Vertrag, da ja nur der Schenker zu etwas verpflichtet ist.", answer:"✗ Falsch\\n\\nSchenkung ist ein zweiseitiger Vertrag"},
    {id:211, category:"Allgemeines Vertragsrecht", question:"Die sogenannte „Gesellschaft bürgerlichen Rechtes“ gibt seit Einführung des UGB nicht mehr.", answer:"✗ Falsch"},
    {id:212, category:"Wurzelmängel & Nichtigkeit", question:"Dimitri hat Andrea offenbar darüber getäuscht, dass er Russisch kann. Da die Täuschung eines Vertragspartners verboten ist, ist die Vereinbarung gem § 879 ABGB nichtig.", answer:"✗ Falsch\\n\\nTäuschung führt nicht automatisch zur Nichtigkeit des Vertrags (§879 ABGB), sondern nur zur Anfechtbarkeit"},
    {id:213, category:"Wurzelmängel & Nichtigkeit", question:"Es liegt lediglich schlichte Unmöglichkeit vor, da die Leistung zwar nicht von Dimitri, aber von jemanden anderem vorgenommen werden kann — der Vertrag ist daher gültig.", answer:"✗ Falsch\\n\\nEs liegt anfängliche objektive Unmöglichkeit vor — Dimitri konnte nie Russisch, daher war die Leistung von Anfang an unmöglich"},
    {id:214, category:"Allgemeines Vertragsrecht", question:"Da Dimitri die Leistung nicht erbringen kann, kann Andrea gem ABGB vorgehen. Sie kann den Vertrag auflösen und muss daher auch nicht €100 an Dimitri zahlen.", answer:"✓ Richtig"},
    {id:215, category:"Wurzelmängel & Nichtigkeit", question:"Sollte Andrea in der Folge die Übersetzungsleistung von jemanden anderem für angemessene €150 erbringen lassen, kann sie Dimitri gem §921 ABGB den Ersatz dieser €150 verlangen.", answer:"✗ Falsch\\n\\nDa der Vertrag nichtig ist, besteht kein Schadensersatzanspruch"},
    {id:216, category:"Wurzelmängel & Nichtigkeit", question:"Da Udo doppelt so viel wie den wahren Wert bezahlt hat, kann der den Vertrag wegen laesio enormis (§934 ABGB) anfechten. Mario kann jedoch den Differenzbetrag zahlen, um den Vertrag aufrecht zu erhalten.", answer:"✓ Richtig"},
    {id:217, category:"Wurzelmängel & Nichtigkeit", question:"Da ein auffallendes Missverhältnis von Leistung und Gegenleistung vorliegt, Udo bei Vertragsabschluss in einer Zwangslage war und Mario diesen Umstand ausgenützt hat, kann Udo die Vertragsaufhebung wegen Wuchers begehren (§879 Abs 2 Z 4 ABGB).", answer:"✓ Richtig"},
    {id:218, category:"Irrtum & Täuschung", question:"Da Udo keine Ahnung vom wahren Wert des Ersatzteils hatte, unterlag er einem Wertirrtum, der als Geschäftsirrtum zur Anfechtung gem §871 ABGB berechtigt.", answer:"✗ Falsch\\n\\nEin Wertirrtum ist kein Geschäftsirrtum, sondern ein unbeachtlicher Motivirrtum"},
    {id:219, category:"Gewährleistung", question:"Da das Ersatzteil einwandfrei funktioniert, ist eine Wandlung gem §932 Abs 4 ABGB ausgeschlossen.", answer:"✓ Richtig\\n\\nWandlung ist nur möglich, wenn die Ware mangelhaft ist"},
    {id:220, category:"Gewährleistung", question:"Da der Preis deutlich höher ist, kann Udo eine Preisminderung gem §932 Abs 4 ABGB begehren.", answer:"✗ Falsch\\n\\nPreisminderung greift nur bei mangelhafter Ware — hier gibt es keinen Mangel, nur einen überhöhten Preis"},
    {id:221, category:"Gewährleistung", question:"Udos Verzweiflung deutet darauf hin, dass er bei Abschluss des Vertrags mit Mario nicht geschäftsfähig war (§865 Abs 1 iVm §24 ABGB), weshalb der Vertrag von Anfang an unwirksam war.", answer:"✗ Falsch\\n\\nVerzweiflung allein macht jemanden nicht geschäftsunfähig"},
    {id:222, category:"Allgemeines Vertragsrecht", question:"Da Udo doppelt so viel wie den wahren Wert des Ersatzteils gezahlt hat, kann er die Lieferung eines zweiten derartigen Teils verlangen.", answer:"✗ Falsch\\n\\nÜberzahlung gibt keinen Anspruch auf eine zweite Lieferung"},
    {id:223, category:"Kaufvertrag & Eigentumsübertragung", question:"Ein Vertrag kommt stets zwischen einem Rechtssubjekt und einem Rechtsobjekt zustande.", answer:"✗ Falsch\\n\\nzwischen zwei Rechtssubjekten"},
    {id:224, category:"Verzug", question:"Im vorliegenden Fall ist die Vertragserfüllung während Schuldnerverzug durch Zufall unmöglich geworden", answer:"✓ Richtig"},
    {id:225, category:"Allgemeines Vertragsrecht", question:"Der Vertrag zerfällt von selbst", answer:"✗ Falsch\\n\\nEin Vertrag zerfällt nicht automatisch — er wird wegen nachträglicher Unmöglichkeit aufgelöst"},
    {id:226, category:"Schadenersatz", question:"Nach Vertragsaufhebung kann Anna einen Schadensersatzanspruch iHv €500 geltend machen (Differenzanspruch).", answer:"✓ Richtig"},
    {id:227, category:"Allgemeines Vertragsrecht", question:"Fritz und Franz können wegen Wegfall der Geschäftsgrundlage (der Umzug wurde abgesagt) die Aufhebung des Balkonplatz-Mietvertrages verlangen.", answer:"✓ Richtig\\n\\n§901 ABGB: Wegfall der Geschäftsgrundlage"},
    {id:228, category:"Allgemeines Vertragsrecht", question:"Die richtige Lösung des Falles (Fritz/Franz) ergibt sich aus §871 ABGB.", answer:"✗ Falsch\\n\\n§901 ABGB (Wegfall der Geschäftsgrundlage), nicht §871 (Irrtum)"},
    {id:229, category:"Allgemeines Vertragsrecht", question:"Oma will Enkelin nach bestandener LAP ein Moped verschenken und übergibt ihr, ohne das Ergebnis der LAP zu wissen die Schlüssel. Enkelin besteht jedoch nicht. Darf die Enkelin das Moped trotzdem behalten?", answer:"✗ Falsch\\n\\nNein — der Schenkungsvertrag unterliegt einem Motivirrtum (Oma glaubte die LAP sei bestanden)"},
    {id:230, category:"Irrtum & Täuschung", question:"Handelt es sich um einen Motivirrtum?", answer:"✓ Richtig\\n\\nOma glaubte irrtümlich, die Enkelin habe die LAP bestanden"},
    {id:231, category:"Allgemeines Vertragsrecht", question:"Kann die Oma das Moped zurückfordern?", answer:"✓ Richtig\\n\\nDa der Motivirrtum bei Schenkungen beachtlich ist (§901 ABGB)"},
    {id:232, category:"Allgemeines Vertragsrecht", question:"Braucht es Einverständnis der Eltern?", answer:"✗ Falsch"},
    {id:233, category:"Wurzelmängel & Nichtigkeit", question:"X kauft von Kunsthändler Statue um € 10.000 vom bekannten Künstler K. nach 4 Jahren will er die Statue verkaufen und kommt drauf, dass sie nicht von K ist nur € 500 Wert ist. Kann wegen Wucher klagen", answer:"✗ Falsch\\n\\nFrist für Wucher: 3 Jahre — bereits abgelaufen (Kauf war vor 4 Jahren)"},
    {id:234, category:"Gewährleistung", question:"X kann wegen Gewährleistung oder Irrtum klagen (Kunsthändler-Fall).", answer:"✗ Falsch\\n\\nFrist je 3 Jahre — beide Fristen bereits abgelaufen"},
    {id:235, category:"Allgemeines Vertragsrecht", question:"X kann wegen List klagen (Kunsthändler-Fall).", answer:"✓ Richtig\\n\\nFrist für List (arglistige Täuschung): 30 Jahre"},
    {id:236, category:"Schadenersatz", question:"Der Student S fährt mit dem GVB –Bus zur Uni und kauft sich beim Einsteigen ein Ticket beim Automaten. Er setzt sich auf einen Sitz, der nicht vom Fahrer geprüft wurde. Während der Fahrt bricht der Sitz hinunter und S verletzt sich dabei. Er verlangt Schmerzensgeld von der GVB, jedoch die weigert sich vehement, weil sie direkt neben dem Ticketautomaten die AGB aufgehängt haben und die eine FETT gedruckte Klausel beinhaltet, in der eine Haftung ausgeschlossen wird. S sagt, dass er die Klausel nicht gesehen hat und so ein Haftungsausschluss sowieso nicht möglich ist. Ist dieser Haftungsausschluss gültig und muss die GVB-Schadenersatz zahlen?", answer:"✗ Falsch\\n\\nHaftungsausschluss ist NICHT wirksam und Schadenersatz muss gezahlt werden"},
    {id:237, category:"Allgemeines Vertragsrecht", question:"Am Dienstag um 13 Uhr ist ein Vertrag zwischen V und K geschlossen worden.", answer:"✓ Richtig"},
    {id:238, category:"Allgemeines Vertragsrecht", question:"Es gibt einen gültigen Vertrag zwischen V und N", answer:"✗ Falsch\\n\\nVertrag ist zwischen V und K, nicht zwischen V und N"},
    {id:239, category:"Allgemeines Vertragsrecht", question:"Am Dienstag um 18 Uhr wird K Eigentümer des PC", answer:"✗ Falsch\\n\\nEigentum geht erst mit Modus (Übergabe) über, die noch nicht stattgefunden hat"},
    {id:240, category:"Allgemeines Vertragsrecht", question:"V ist noch Eigentümer des PC", answer:"✓ Richtig"}
  ],

  mc: [
    {id:1, category:"Verzug", question:"Verzug stellt ein dauerhaftes Leistungshindernis dar.", options:["Richtig","Falsch"], correct:1},
    {id:2, category:"Stellvertretung & Vollmacht", question:"Die Vollmacht ist hinsichtlich ihres Umfanges notwendigerweise stets gleich wie das Innenverhältnis zwischen Geschäftsherren und Vertreter ausgestaltet.", options:["Richtig","Falsch"], correct:1},
    {id:3, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel ziehen stets Gesamtnichtigkeit eines Rechtsgeschäfts nach sich", options:["Richtig","Falsch"], correct:1},
    {id:4, category:"Schadenersatz", question:"Unter Adäquanzprinzip versteht man den Grundsatz, dass ohne Verschulden kein Schadensersatz geleistet werden muss.", options:["Richtig","Falsch"], correct:1},
    {id:5, category:"Verjährung", question:"Tritt Verjährung ein, geht zwar die Klagbarkeit verloren, nicht jedoch das Recht an sich", options:["Richtig","Falsch"], correct:0},
    {id:6, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Leihvertrag ist ein Realvertrag", options:["Richtig","Falsch"], correct:0},
    {id:7, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Verwahrungsvertrag ist ein Realvertrag", options:["Richtig","Falsch"], correct:0},
    {id:8, category:"Kaufvertrag & Eigentumsübertragung", question:"Ein Kaufvertrag über eine Liegenschaft ist ein Realvertrag.", options:["Richtig","Falsch"], correct:1},
    {id:9, category:"Gewährleistung", question:"Preisminderung und Wandlung werden als primäre Gewährleistungsbehelfe bezeichnet", options:["Richtig","Falsch"], correct:1},
    {id:10, category:"Allgemeines Vertragsrecht", question:"Ein 15- Jähriger darf über alle ihm überlassenen Gegenstände unumschränkt verfügen.", options:["Richtig","Falsch"], correct:1},
    {id:11, category:"Wurzelmängel & Nichtigkeit", question:"Die Laesio enormis ist den Wurzelmängel zuzurechnen.", options:["Richtig","Falsch"], correct:0},
    {id:12, category:"Wurzelmängel & Nichtigkeit", question:"Laesio enormis liegt bei einem Wertverhältnis von 50:100 vor.", options:["Richtig","Falsch"], correct:1},
    {id:13, category:"Allgemeines Vertragsrecht", question:"Als Anerkenntnis bezeichnet man einen Vertrag, mit dem Streitpunkte in einem Vertragsverhältnis dadurch ausgeräumt werden, dass ein Partner (nicht beide) nachgibt.", options:["Richtig","Falsch"], correct:0},
    {id:14, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — liegt nur bei Streitigkeiten zwischen internationalen Organisationen vor.", options:["Richtig","Falsch"], correct:1},
    {id:15, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — liegt immer dann vor, wenn Berührungspunkte zu mehr als einen Staat bestehen.", options:["Richtig","Falsch"], correct:0},
    {id:16, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — kann niemals vorliegen, wenn die Streitparteien im selben Staat wohnen.", options:["Richtig","Falsch"], correct:1},
    {id:17, category:"Internationales Privatrecht", question:"Ein Sachverhalt mit Auslandberührung — wird stets nach internationalem Einsichtsrecht beurteilt.", options:["Richtig","Falsch"], correct:1},
    {id:18, category:"Forderungsabtretung", question:"Anders als ein bloßer Gläubigerwechsel (Zession) oder ein bloßer Schuldnerwechsel (Schuldübernahme) ist die Übertragung einer Vertragsposition als Ganzes (Vertragsübernahme) nicht möglich (und aus diesem Grund nirgendwo gesetzlich geregelt).", options:["Richtig","Falsch"], correct:1},
    {id:19, category:"Kaufvertrag & Eigentumsübertragung", question:"Die Eigentumseinverleibung im Grundbuch hat grundsätzlich konstruktive Wirkung.", options:["Richtig","Falsch"], correct:0},
    {id:20, category:"Allgemeines Vertragsrecht", question:"Die Vereinbarung eines Kündigungsverzeichnis für eine vorweg begrenzte Zeit.", options:["Richtig","Falsch"], correct:1},
    {id:21, category:"Sittenwidrigkeit", question:"Eine Vereinbarung, wonach sich ein Einzelhändler verpflichtet, sein gesamtes Warensortiment ausschließlich bei einem bestimmten Großhändler zu beziehen.", options:["Richtig","Falsch"], correct:0},
    {id:22, category:"Geschäftsfähigkeit", question:"Die Geschäftsfähigkeit beginnt mit der Lebendgeburt und endet mit dem Tod", options:["Richtig","Falsch"], correct:0},
    {id:23, category:"Eigentum & Besitz", question:"Welche der folgenden Aussagen trifft/treffen auf den gutgläubigen Erwerb gemäß §367 ABGB zu: Es muss ein entgeltliches Titelgeschäft vorliegen", options:["Richtig","Falsch"], correct:0},
    {id:24, category:"Allgemeines Vertragsrecht", question:"Gutgläubiger Erwerb §367 ABGB — Es muss um den Erwerb einer unbeweglichen, körperlichen Sache gehen.", options:["Richtig","Falsch"], correct:1},
    {id:25, category:"Allgemeines Vertragsrecht", question:"Gutgläubiger Erwerb §367 ABGB — Der Veräußerer muss hinsichtlich seiner Eigentümerstellung redlich sein.", options:["Richtig","Falsch"], correct:0},
    {id:26, category:"Allgemeines Vertragsrecht", question:"Gutgläubiger Erwerb §367 ABGB — Der Veräußerer muss entweder UN sein oder Vertrauensmann des vorigen Eigentümers, oder der Erwerb muss im Rahmen einer öffentlichen Versteigung stattfinden.", options:["Richtig","Falsch"], correct:0},
    {id:27, category:"Kaufvertrag & Eigentumsübertragung", question:"Gutgläubiger Erwerb §367 ABGB — Es muss eine Übergabe (Modus) erfolgen.", options:["Richtig","Falsch"], correct:0},
    {id:28, category:"Forderungsabtretung", question:"Eine Forderungsabtretung (Zession) ist ein Verfügungsgeschäft", options:["Richtig","Falsch"], correct:0},
    {id:29, category:"Irrtum & Täuschung", question:"Wenn ein Vertrag nach Erbringung einer Leistung (etwa wegen Irrtums) aufgelöst wird, kann die erbrachte Leistung bereicherungsrechtlich zurückgefordert werden.", options:["Richtig","Falsch"], correct:0},
    {id:30, category:"Allgemeines Vertragsrecht", question:"Das Vertragsverhältnis ist beendet, wenn alle Verbindlichkeiten erfüllt wurden.", options:["Richtig","Falsch"], correct:0},
    {id:31, category:"Stellvertretung & Vollmacht", question:"Bei einer wirksamen Stellvertretung kommt das Rechtsgeschäft des Dritten unmittelbar mit dem Vertretenen zustande.", options:["Richtig","Falsch"], correct:0},
    {id:32, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Erklärungen unter Freunden", options:["Richtig","Falsch"], correct:1},
    {id:33, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Erklärungen im Familienkreis", options:["Richtig","Falsch"], correct:1},
    {id:34, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Zeitungsinseraten", options:["Richtig","Falsch"], correct:0},
    {id:35, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Erklärungen am Telefon", options:["Richtig","Falsch"], correct:1},
    {id:36, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt im Allgemeinen bei — Scherzerklärungen", options:["Richtig","Falsch"], correct:0},
    {id:37, category:"Gewährleistung", question:"Ist ein Mangel geringfügig, kann ein Wandlungsbegehren keinen Erfolg haben.", options:["Richtig","Falsch"], correct:0},
    {id:38, category:"Verjährung", question:"Für die Anfechtung des Rechtsgeschäfts wegen Irrtums gilt eine Verjährungsfrist von drei Jahren ab Kenntnis des Irrtums.", options:["Richtig","Falsch"], correct:1},
    {id:39, category:"Gewährleistung", question:"Eine Konkurrenz ist denkbar… … zwischen Gewährleistungsbehelfen und Irrtumsanfechtung", options:["Richtig","Falsch"], correct:0},
    {id:40, category:"Gewährleistung", question:"Eine Konkurrenz ist denkbar — zwischen Gewährleistungsbehelfen und Nichterfüllungsbehelfen", options:["Richtig","Falsch"], correct:1},
    {id:41, category:"Wurzelmängel & Nichtigkeit", question:"Eine Konkurrenz ist denkbar — zwischen Irrtumsanfechtung und laesio enormis", options:["Richtig","Falsch"], correct:0},
    {id:42, category:"Irrtum & Täuschung", question:"Eine Konkurrenz ist denkbar — zwischen Nichterfüllungsbehelfen und Irrtumsanfechtung", options:["Richtig","Falsch"], correct:0},
    {id:43, category:"Schadenersatz", question:"Eine Konkurrenz ist denkbar — zwischen Schadenersatzansprüchen und Gewährleistungsbehelfen", options:["Richtig","Falsch"], correct:0},
    {id:44, category:"Kaufvertrag & Eigentumsübertragung", question:"Konsumenten können von einem Kaufvertrag binnen 2 Wochen unter Vorlage der Rechnung zurücktreten (allgemeines Rücktrittsrecht nach KSchG)", options:["Richtig","Falsch"], correct:1},
    {id:45, category:"Verzug", question:"Gerät der Schuldner in Teilverzug, kann der Gläubiger bei Unteilbarkeit der Leistung vom gesamten Vertrag zurücktreten.", options:["Richtig","Falsch"], correct:0},
    {id:46, category:"Vertragsabschluss", question:"Verträge kommen durch Angebot und Nachfrage zustande", options:["Richtig","Falsch"], correct:1},
    {id:47, category:"Konsumentenschutz", question:"Im Konsument Schutzgesetz sind einige spezielle Rücktrittsrechte geregelt.", options:["Richtig","Falsch"], correct:0},
    {id:48, category:"Internationales Privatrecht", question:"Wenn die beteiligten Personen dieselbe Staatsbürgerschaft haben, liegt sicher kein Sachverhalt mit Auslandberührung vor.", options:["Richtig","Falsch"], correct:1},
    {id:49, category:"Vertragsabschluss", question:"Wer in der Zeitung sein Auto zum Verkauf inseriert, macht ein Verbindliches Angebot.", options:["Richtig","Falsch"], correct:1},
    {id:50, category:"Eigentum & Besitz", question:"Der Dieb einer Sache hat die Rechtsstellung eines Besitzers, da er mit der gestohlenen Sache verfährt, als wäre sie seine eigene (z.B. veräußert er sie)", options:["Richtig","Falsch"], correct:1},
    {id:51, category:"Internationales Privatrecht", question:"Österreich hat mit dem IPRG (Internationales Privatrecht) ein Autonomes Koalitionsrecht", options:["Richtig","Falsch"], correct:0},
    {id:52, category:"Irrtum & Täuschung", question:"Die Möglichkeit zur Anfechtung eines Vertrags wegen Irrtums verjährt binnen 3 Jahren ab Vertragserfüllung.", options:["Richtig","Falsch"], correct:1},
    {id:53, category:"Wurzelmängel & Nichtigkeit", question:"Ein Wurzelmangel setzt stets einen gültig zustande gekommen Vertrag voraus.", options:["Richtig","Falsch"], correct:1},
    {id:54, category:"Konsumentenschutz", question:"Das Transparenzgebot gilt für alle vertraglichen Vereinbarungen zwischen Unternehmen und Verbrauchern.", options:["Richtig","Falsch"], correct:1},
    {id:55, category:"Gewährleistung", question:"Eine Leistung ist mangelhaft, wenn gewöhnlich vorausgesetzte Eigenschaften fehlen", options:["Richtig","Falsch"], correct:0},
    {id:56, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Legalzession", options:["Richtig","Falsch"], correct:0},
    {id:57, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einem Schuldbeitritt (ein zusätzlicher Schuldner tritt hinzu, kein Gläubigerwechsel)", options:["Richtig","Falsch"], correct:1},
    {id:58, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Sicherungsabtretung", options:["Richtig","Falsch"], correct:0},
    {id:59, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Mantelzession", options:["Richtig","Falsch"], correct:0},
    {id:60, category:"Forderungsabtretung", question:"Ein Gläubigerwechsel findet statt bei — einer Novation (Alte Schuld wird durch neue ersetzt)", options:["Richtig","Falsch"], correct:1},
    {id:61, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen: Die Dienstbarkeit", options:["Richtig","Falsch"], correct:0},
    {id:62, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen — Die Reallast", options:["Richtig","Falsch"], correct:0},
    {id:63, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen — Die Dienstleistung", options:["Richtig","Falsch"], correct:1},
    {id:64, category:"Eigentum & Besitz", question:"Zu den dinglichen Rechten zählen — Der Besitz", options:["Richtig","Falsch"], correct:1},
    {id:65, category:"Allgemeines Vertragsrecht", question:"Zu den dinglichen Rechten zählen — Das Baurecht", options:["Richtig","Falsch"], correct:0},
    {id:66, category:"Allgemeines Vertragsrecht", question:"Die Volljährigkeit erreicht man mit dem 19. Geburtstag", options:["Richtig","Falsch"], correct:1},
    {id:67, category:"Eigentum & Besitz", question:"Miteigentum kann nur aus ohne Wertverlust real teilbaren Sachen bestehen.", options:["Richtig","Falsch"], correct:1},
    {id:68, category:"Allgemeines Vertragsrecht", question:"Was ist Voraussetzung für das wirksame Zustandekommen eines Vertrags? Die Parteien müssen sich einig sein", options:["Richtig","Falsch"], correct:0},
    {id:69, category:"Irrtum & Täuschung", question:"Es darf kein Motivirrtum vorliegen", options:["Richtig","Falsch"], correct:1},
    {id:70, category:"Allgemeines Vertragsrecht", question:"Der Inhalt des Vertrags darf nicht rechtlich unmöglich sein", options:["Richtig","Falsch"], correct:0},
    {id:71, category:"Allgemeines Vertragsrecht", question:"Die Erklärungen der Parteien müssen ernst gemeint sein", options:["Richtig","Falsch"], correct:0},
    {id:72, category:"Allgemeines Vertragsrecht", question:"Der Vertrag muss vor Zeugen geschlossen werden", options:["Richtig","Falsch"], correct:1},
    {id:73, category:"Allgemeines Vertragsrecht", question:"Ein berühmtes Beispiel für den Wegfall der Geschäftsgrundlagen ist der „Krönungszug“ Fall", options:["Richtig","Falsch"], correct:0},
    {id:74, category:"Sittenwidrigkeit", question:"Der OGH definiert „Verletzung der guten Sitten“ als Gefährdung anerkannter Ordnungen, Freiheitsbeschränkungen, Ausnutzung einer Übermachtposition, schwere Äquivalenzstörungen oder Manifestation einer verwerflichen Gesinnung.", options:["Richtig","Falsch"], correct:0},
    {id:75, category:"Verzug", question:"Bei objektivem Verzug — kann der Gläubiger auf Erfüllung beharren", options:["Richtig","Falsch"], correct:0},
    {id:76, category:"Verzug", question:"Bei objektivem Verzug — kann der Gläubiger unter Setzung einer angemessenen Nachfrist vom Vertrag zurücktreten", options:["Richtig","Falsch"], correct:0},
    {id:77, category:"Verzug", question:"Bei objektivem Verzug — wird der Vertrag ex lege aufgelöst", options:["Richtig","Falsch"], correct:1},
    {id:78, category:"Verzug", question:"Bei objektivem Verzug — liegt ein Verschulden des Schuldners vor", options:["Richtig","Falsch"], correct:1},
    {id:79, category:"Verzug", question:"Bei objektivem Verzug — gelten §§ 922 ff ABGB", options:["Richtig","Falsch"], correct:1},
    {id:80, category:"Allgemeines Vertragsrecht", question:"Wenn der Käufer die Kaufsache bei Fälligkeit nicht wie vereinbart abholt und sie danach beim Verkäufer gestohlen wird, steht dem Verkäufer dennoch der Kaufpreis zu.", options:["Richtig","Falsch"], correct:0},
    {id:81, category:"Kaufvertrag & Eigentumsübertragung", question:"Beim Erwerb einer Liegenschaft, z.B. einer Wohnung, erwirbt man das Eigentum durch Schlüsselübergabe. Die Eintragung im Grundbuch ist zwar ratsam, aber nicht unbedingt notwendig.", options:["Richtig","Falsch"], correct:1},
    {id:82, category:"Wurzelmängel & Nichtigkeit", question:"Wer aufgrund eines nichtigen Vertrages eine Leistung erbringt, ist selbst schuld und kann diese Leistung nicht zurückfordern.", options:["Richtig","Falsch"], correct:1},
    {id:83, category:"Gewährleistung", question:"Beim Kauf in Pausch und Bogen kann der Übernehmer im Fall mangelhafter Leistung zwar Verbesserung iwS und Preisminderung begehren eine Wandlung kommt hingegen nicht in Frage", options:["Richtig","Falsch"], correct:0},
    {id:84, category:"Gewährleistung", question:"Eine Leistung ist mangelhaft, wenn gewöhnlich vorausgesetzte Eigenschaften fehlen.", options:["Richtig","Falsch"], correct:0},
    {id:85, category:"Forderungsabtretung", question:"Wird der Schuldner von der Zession verständigt, kann er trotzdem weiterhin schuldbefreiend an dem Altgläubiger leisten.", options:["Richtig","Falsch"], correct:1},
    {id:86, category:"Eigentum & Besitz", question:"Ein Eigentumsvorbehalt… … bewirkt, dass der Eigentumübergang auflösend befristet ist.", options:["Richtig","Falsch"], correct:1},
    {id:87, category:"Allgemeines Vertragsrecht", question:"Ein Eigentumsvorbehalt — verschafft dem Veräußerer in der Insolvenz des Erwerbers ein Aussonderungsrecht", options:["Richtig","Falsch"], correct:0},
    {id:88, category:"Allgemeines Vertragsrecht", question:"Ein Eigentumsvorbehalt — ergibt sich bei Kreditkäufen schon aus zwingenden gesetzlichen Vorschriften", options:["Richtig","Falsch"], correct:1},
    {id:89, category:"Eigentum & Besitz", question:"Ein Eigentumsvorbehalt — lässt das Eigentum erst bei vollständiger Zahlung des vertraglich vereinbarten Entgelts übergehen", options:["Richtig","Falsch"], correct:0},
    {id:90, category:"Allgemeines Vertragsrecht", question:"Ein Eigentumsvorbehalt — ermöglicht es dem Veräußerer grundsätzlich, die veräußerte Sache im Fall der Nichtzahlung des Entgelts auch von einem Dritten herauszuverlangen.", options:["Richtig","Falsch"], correct:0},
    {id:91, category:"Allgemeines Vertragsrecht", question:"Bei Fälligkeit der Sachleistung trägt in der Regel der Sachgläubiger die Preisgefahr. Wird der Leistungsgegenstand zerstört, muss der Sachgläubiger dennoch den Preis bezahlen.", options:["Richtig","Falsch"], correct:1},
    {id:92, category:"Allgemeines Vertragsrecht", question:"Die Erfüllung einer Gattungsschuld kann niemals unmöglich werden.", options:["Richtig","Falsch"], correct:1},
    {id:93, category:"Allgemeines Vertragsrecht", question:"Die Erfüllung einer Gattungsschuld kann unmöglich werden.", options:["Richtig","Falsch"], correct:0},
    {id:94, category:"Schadenersatz", question:"Trifft den Schuldner (erstellt Leistung) am Unmöglich-Werden einer Leistung ein Verschulden, kann der Gläubiger (fragt nach Leistung) Schadenersatz verlangen.", options:["Richtig","Falsch"], correct:0},
    {id:95, category:"Wurzelmängel & Nichtigkeit", question:"Verträge, bei denen die öffentlichen Interessen (Drogenhandel) gegen die Gültigkeit sprechen, sind absolut nichtig.", options:["Richtig","Falsch"], correct:0},
    {id:96, category:"Allgemeines Vertragsrecht", question:"Nach Vertragsabschluss können Veränderungen des Vertragsinhalt nicht einseitig vorgenommen werden", options:["Richtig","Falsch"], correct:0},
    {id:97, category:"Verzug", question:"Bei Gläubigerverzug (Annahmeverzug) haftet der Schuldner nur noch für grobes Verschulden.", options:["Richtig","Falsch"], correct:0},
    {id:98, category:"Allgemeines Vertragsrecht", question:"Juristische Personen handeln durch ihre Organe", options:["Richtig","Falsch"], correct:0},
    {id:99, category:"Stellvertretung & Vollmacht", question:"Ein sogenannter „Mittelbarer Stellvertreter“ handelt im eigenen Namen, aber auf fremde Rechnung", options:["Richtig","Falsch"], correct:0},
    {id:100, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — mehrdeutig ist", options:["Richtig","Falsch"], correct:0},
    {id:101, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — unvollständig ist", options:["Richtig","Falsch"], correct:0},
    {id:102, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — unverständlich ist", options:["Richtig","Falsch"], correct:0},
    {id:103, category:"Allgemeines Vertragsrecht", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — faktisch unmöglich", options:["Richtig","Falsch"], correct:1},
    {id:104, category:"Sittenwidrigkeit", question:"Dissens kann insbesondere dann gegeben sein, wenn das Vereinbarte — sittenwidrig ist", options:["Richtig","Falsch"], correct:1},
    {id:105, category:"Wurzelmängel & Nichtigkeit", question:"Absolute Nichtigkeit kann von jedermann geltend gemacht werden.", options:["Richtig","Falsch"], correct:0},
    {id:106, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — Scherzerklärungen", options:["Richtig","Falsch"], correct:0},
    {id:107, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — Werbeaussagen", options:["Richtig","Falsch"], correct:0},
    {id:108, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — sogenannten Bühnenerklärungen", options:["Richtig","Falsch"], correct:0},
    {id:109, category:"Vertragsabschluss", question:"Ein rechtsgeschäftlicher Bindungswille fehlt in der Regel bei — Lehrveranstaltungen", options:["Richtig","Falsch"], correct:0},
    {id:110, category:"Allgemeines Vertragsrecht", question:"Geldschulden sind im Zweifel durch Giroüberweisungen zu bezahlen", options:["Richtig","Falsch"], correct:1},
    {id:111, category:"Eigentum & Besitz", question:"Die Ersitzung ist eine Form des originärem Eigentumserwerb", options:["Richtig","Falsch"], correct:0},
    {id:112, category:"Allgemeines Vertragsrecht", question:"Ob ein Rechtsgeschäft bei einem Gesetzesverbot iSd § 879 ABGB richtig ist, ergibt sich aus dem Schutzzweck der verletzten Norm.", options:["Richtig","Falsch"], correct:0},
    {id:113, category:"Eigentum & Besitz", question:"Ein Schenkungsversprechen ohne Übergabe bedarf zu seiner Gültigkeit eines Notariatsakt.", options:["Richtig","Falsch"], correct:0},
    {id:114, category:"Verzug", question:"Die gesetzlichen Verzugszinsen betragen nach dem ABGB 4%.", options:["Richtig","Falsch"], correct:0},
    {id:115, category:"Schadenersatz", question:"Schadensersatz ist im Allgemeinen dann zu leisten, wenn man rechtswidrig und schuldhaft einen Schaden verursacht.", options:["Richtig","Falsch"], correct:0},
    {id:116, category:"Gewährleistung", question:"Eine Konkurrenz zwischen Nichterfüllungs- und Gewährleistungsbehelfen ist ausgeschlossen", options:["Richtig","Falsch"], correct:0},
    {id:117, category:"Gewährleistung", question:"Die Gewährleistungspflicht kann grundsätzlich von den Vertragsparteien durch entsprechende vertragliche Vereinbarung verlängert oder verkürzt werden", options:["Richtig","Falsch"], correct:0},
    {id:118, category:"Schadenersatz", question:"Nicht jeder zugefügte Schaden ist ersatzfähig", options:["Richtig","Falsch"], correct:0},
    {id:119, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel zieht stets die Gesamtnichtigkeit eines Rechtsgeschäfts nach sich", options:["Richtig","Falsch"], correct:1},
    {id:120, category:"Verzug", question:"Bei Gläubigerverzug haftet der Schuldner nur noch grobes Verschulden.", options:["Richtig","Falsch"], correct:0},
    {id:121, category:"Forderungsabtretung", question:"Eine Forderungsabtretung bedarf eines Rechtsgrundes, um wirksam zu sein. Als Rechtsgrund kommt etwa ein Factoring-Vertrag in Frage.", options:["Richtig","Falsch"], correct:0},
    {id:122, category:"Allgemeines Vertragsrecht", question:"Bei Kreditkauf trägt das Insolvenzrisiko der Käufer.", options:["Richtig","Falsch"], correct:1},
    {id:123, category:"Allgemeines Vertragsrecht", question:"Ein Baby ist rechtsfähig und kann daher z.B. Eigentümer eines großen Hauses sein", options:["Richtig","Falsch"], correct:0},
    {id:124, category:"Allgemeines Vertragsrecht", question:"Bei Spezialschuld trägt der Sachschuldner die Leistungsgefahr", options:["Richtig","Falsch"], correct:0},
    {id:125, category:"Gewährleistung", question:"Ziel der Gewährleistung ist die Herstellung von subjektiver Äquivalenz.", options:["Richtig","Falsch"], correct:0},
    {id:126, category:"Kaufvertrag & Eigentumsübertragung", question:"Anders als nach ABGB kommt im UN-Kaufrecht ein Kaufvertrag grundsätzlich nicht durch Konsens, sondern durch Warensendung zustande", options:["Richtig","Falsch"], correct:1},
    {id:127, category:"Verzug", question:"Die Rechte auf Gewährleistung können grundsätzlich neben jenen wegen Verzugs geltend gemacht werden.", options:["Richtig","Falsch"], correct:1},
    {id:128, category:"Allgemeines Vertragsrecht", question:"Der Widerruf einer Schenkung ist ausnahmslos ausgeschlossen", options:["Richtig","Falsch"], correct:1},
    {id:129, category:"Gewährleistung", question:"Die Rechte aus Gewährleistung können grundsätzlich neben jenen aus Irrtum geltend gemacht werden.", options:["Richtig","Falsch"], correct:0},
    {id:130, category:"Konsumentenschutz", question:"Das KSchG enthält typischerweise relativ zwingende Normen", options:["Richtig","Falsch"], correct:0},
    {id:131, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Darlehensvertrag ist ein Realvertrag", options:["Richtig","Falsch"], correct:1},
    {id:132, category:"Allgemeines Vertragsrecht", question:"Wird aufgrund eines bereits erfüllten Vertrages irrtümlich nochmals geleistet, steht dem Leistenden eine Leistungskondition offen.", options:["Richtig","Falsch"], correct:0},
    {id:133, category:"Schadenersatz", question:"Adäquanz heißt, dass ohne Verschulden kein Schadenersatz geleistet werden kann.", options:["Richtig","Falsch"], correct:1},
    {id:134, category:"Allgemeines Vertragsrecht", question:"Vorsatz ist eine auffallende und ungewöhnliche Nachlässigkeit", options:["Richtig","Falsch"], correct:1},
    {id:135, category:"Gewährleistung", question:"Preisminderung und Wandlung werden als primäre Gewährleistungsbehelfe bezeichnet", options:["Richtig","Falsch"], correct:1},
    {id:136, category:"Allgemeines Vertragsrecht", question:"Verschuldet der Schuldner die Unmöglichkeit der Leistung und hält der Gläubiger den Vertrag aufrecht so kann er den Differenzanspruch geltend machen", options:["Richtig","Falsch"], correct:1},
    {id:137, category:"Internationales Privatrecht", question:"Bei internationalen Sachverhalten kommt statt des ABGB und des UGB das IPRG zur Anwendung.", options:["Richtig","Falsch"], correct:1},
    {id:138, category:"Allgemeines Vertragsrecht", question:"Beim drittfinanzierten Kauf wird der Kaufpreis dem Käufer nicht vom Verkäufer, sondern von einem mit diesem zusammenarbeitenden Dritten kreditiert.", options:["Richtig","Falsch"], correct:0},
    {id:139, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist in folgenden Fällen beachtlich: — Wenn der Vertrag ohne den Irrtum nicht abgeschlossen worden wäre.", options:["Richtig","Falsch"], correct:1},
    {id:140, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — bei Schenkung", options:["Richtig","Falsch"], correct:0},
    {id:141, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — ... wenn der Motivirrtum listig veranlasst worden ist", options:["Richtig","Falsch"], correct:0},
    {id:142, category:"Konsumentenschutz", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — in Verbraucherverträgen", options:["Richtig","Falsch"], correct:1},
    {id:143, category:"Irrtum & Täuschung", question:"Ein Motivirrtum ist folgenden Fällen beachtlich: — wenn das Motiv ausdrücklich zur Bedingung gemacht worden ist", options:["Richtig","Falsch"], correct:0},
    {id:144, category:"Allgemeines Vertragsrecht", question:"Beim Kauf sind die Leistungen grundsätzlich Zug um Zug zu erbringen", options:["Richtig","Falsch"], correct:0},
    {id:145, category:"Wurzelmängel & Nichtigkeit", question:"Verträge, bei denen die öffentlichen Interessen gegen die Gültigkeit sprechen, sind absolut nichtig", options:["Richtig","Falsch"], correct:0},
    {id:146, category:"Schadenersatz", question:"Trifft den Schuldner am Unmöglich-werden einer Leistung ein Verschulden, kann der Gläubiger Schadenersatz verlangen", options:["Richtig","Falsch"], correct:0},
    {id:147, category:"Wurzelmängel & Nichtigkeit", question:"Ob ein Rechtsgeschäft bei einem Gesetzesverstoß iSd § 879 ABGB überhaupt in irgendeiner Form nichtig ist, ergibt sich aus dem Schutzzweck der verletzten Norm.", options:["Richtig","Falsch"], correct:0},
    {id:148, category:"Kaufvertrag & Eigentumsübertragung", question:"Der Leihvertrag ist ein Realvertrag", options:["Richtig","Falsch"], correct:0},
    {id:149, category:"Gewährleistung", question:"Ist ein Mangel geringfügig, kann ein Wandlungsbegehren keinen Erfolg haben", options:["Richtig","Falsch"], correct:0},
    {id:150, category:"Irrtum & Täuschung", question:"Irrtum ist unbeachtlich, wenn der Vertrag auch bei Kenntnis der wahren Sachlage, aber mit anderem Inhalt abgeschlossen worden wäre.", options:["Richtig","Falsch"], correct:1},
    {id:151, category:"Kaufvertrag & Eigentumsübertragung", question:"Titel und Modus nur beim derivaten nicht aber beim originären Eigentumserwerb gegeben", options:["Richtig","Falsch"], correct:1},
    {id:152, category:"Konsumentenschutz", question:"Transparenzgebot gilt für Verträge zwischen Unternehmen und Verbraucher.", options:["Richtig","Falsch"], correct:1},
    {id:153, category:"Forderungsabtretung", question:"Forderungsabtretung ist ein Verfügungsgeschäft", options:["Richtig","Falsch"], correct:0},
    {id:154, category:"Allgemeines Vertragsrecht", question:"Verletzt ein Treuhänder seine Pflichten gegenüber dem Treugeber, ist auch der Vertrag mit dem Dritten stets unwirksam.", options:["Richtig","Falsch"], correct:1},
    {id:155, category:"Vertragstypen", question:"Ist der Werkvertrag ein Auftrag?", options:["Richtig","Falsch"], correct:1},
    {id:156, category:"Kaufvertrag & Eigentumsübertragung", question:"Zession braucht Modus und Titel", options:["Richtig","Falsch"], correct:0},
    {id:157, category:"Allgemeines Vertragsrecht", question:"Tiere brauchen einen Sachwalter", options:["Richtig","Falsch"], correct:1},
    {id:158, category:"Allgemeines Vertragsrecht", question:"Anerkenntnis ist ein Vertrag, einseitig, unentgeltlicher, gesetzlich nicht geregelter", options:["Richtig","Falsch"], correct:1},
    {id:159, category:"Allgemeines Vertragsrecht", question:"Wenn im ABGB nicht bestimmt ist, dass der Vertrag anders als schriftlich zu erfolgen hat, muss er schriftlich werden.", options:["Richtig","Falsch"], correct:1},
    {id:160, category:"Stellvertretung & Vollmacht", question:"Beim Stellvertreter kann es sein, dass er mehr kann als darf", options:["Richtig","Falsch"], correct:0},
    {id:161, category:"Allgemeines Vertragsrecht", question:"Die Fälligkeit der Leistung steht im Gesetz", options:["Richtig","Falsch"], correct:0},
    {id:162, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: 3 Goldfische", options:["Richtig","Falsch"], correct:0},
    {id:163, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: Ein Wein Jahrgang 1978 der Rebsorte Merlot", options:["Richtig","Falsch"], correct:1},
    {id:164, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: Irgendein Bild von Klimt", options:["Richtig","Falsch"], correct:0},
    {id:165, category:"Allgemeines Vertragsrecht", question:"Gattungsschuld ist: Die Mona Lisa", options:["Richtig","Falsch"], correct:1},
    {id:166, category:"Kaufvertrag & Eigentumsübertragung", question:"A leiht B sein Rad übers Wochenende. Also ist A in der Zeit Eigentümer des Rades, da Titel und Modus gegen sind.", options:["Richtig","Falsch"], correct:1},
    {id:167, category:"Irrtum & Täuschung", question:"Ein Kalkulationsirrtum ist ein Geschäftsirrtum", options:["Richtig","Falsch"], correct:1},
    {id:168, category:"Sittenwidrigkeit", question:"Ein Verstoß gegen die Sitten sind Freiheitsbeschränkungen, schwere Äquivalenzstörungen, Gefährdung anerkannter Ordnungen, die Ausnutzung einer Übermachtposition.", options:["Richtig","Falsch"], correct:0},
    {id:169, category:"Wurzelmängel & Nichtigkeit", question:"Laesio enormis gehört zu den Wurzelmängel.", options:["Richtig","Falsch"], correct:0},
    {id:170, category:"Allgemeines Vertragsrecht", question:"Für einen Bürgen braucht es Zeugen?", options:["Richtig","Falsch"], correct:1},
    {id:171, category:"Allgemeines Vertragsrecht", question:"Vertragsverhältnis beendet, wenn alle Verbindlichkeiten erfüllt sind?", options:["Richtig","Falsch"], correct:0},
    {id:172, category:"Allgemeines Vertragsrecht", question:"Durch § 972 ABGB, List & Drohung muss nicht aufgehoben werden, kann angepasst werden.", options:["Richtig","Falsch"], correct:1},
    {id:173, category:"Gewährleistung", question:"Um Gewährleistung nicht zu verlieren, muss man immer eine Mängelrüge schreiben?", options:["Richtig","Falsch"], correct:1},
    {id:174, category:"Verzug", question:"Konkurrenz zwischen Wurzelmängel und Leistungsstörungen?", options:["Richtig","Falsch"], correct:0},
    {id:175, category:"Allgemeines Vertragsrecht", question:"Tausch & Kauf sind zweiseitige Verträge?", options:["Richtig","Falsch"], correct:0},
    {id:176, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel schließen einen gültig zustande gekommen Vertrag aus?", options:["Richtig","Falsch"], correct:1},
    {id:177, category:"Kaufvertrag & Eigentumsübertragung", question:"B borgt Y für eine Woche sein Fahrrad, für diese Zeit wird Y der Eigentümer da Titel und Modus vorliegen.", options:["Richtig","Falsch"], correct:1},
    {id:178, category:"Allgemeines Vertragsrecht", question:"Das Werkunternehmen muss für sein Werk gewährleisten.", options:["Richtig","Falsch"], correct:0},
    {id:179, category:"Stellvertretung & Vollmacht", question:"Da Tiere nicht geschäftsfähig sind bedürfen sie notwendigerweise einen Stellvertreter, wenn sich am rechtsgeschäftlichen Verkehr teilnehmen.", options:["Richtig","Falsch"], correct:1},
    {id:180, category:"Gewährleistung", question:"Der Ausschluss der Gewährleistung beim Privatkauf", options:["Richtig","Falsch"], correct:0},
    {id:181, category:"Allgemeines Vertragsrecht", question:"Als Vergleich bezeichnet man einen Vertrag, mit dem die Vertragspartei Streitpunkte einer bestehenden Rechtsbeziehung durch beidseitiges Nachgeben ausräumen.", options:["Richtig","Falsch"], correct:0},
    {id:182, category:"Internationales Privatrecht", question:"Die Frage welches materielle Recht im Prozess zu einem internationalen Sachverhalt zur Anwendung gelangt, ist eine Frage des internationalen Zivilprozessrechts (IZPR).", options:["Richtig","Falsch"], correct:1},
    {id:183, category:"Allgemeines Vertragsrecht", question:"Was rechtlich unmöglich ist kann nicht Inhalt eines wirksamen Vertrags sein.", options:["Richtig","Falsch"], correct:0},
    {id:184, category:"Allgemeines Vertragsrecht", question:"Neben den allgemeinen Gerichtsstand können auch Wahlgerichtsstände (besondere Gerichtsstände) für die Zuständigkeit eines Gerichts maßgebend sein.", options:["Richtig","Falsch"], correct:0},
    {id:185, category:"Eigentum & Besitz", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — des Käufers", options:["Richtig","Falsch"], correct:1},
    {id:186, category:"Eigentum & Besitz", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — des Verkäufers", options:["Richtig","Falsch"], correct:0},
    {id:187, category:"Eigentum & Besitz", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — eines Dritten der die Sache von dem Käufer erwerben möchte", options:["Richtig","Falsch"], correct:1},
    {id:188, category:"Allgemeines Vertragsrecht", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — eines Kreditinstituts, das dem Käufer den Erwerb ermöglicht", options:["Richtig","Falsch"], correct:1},
    {id:189, category:"Allgemeines Vertragsrecht", question:"Zweck eines Eigentumsvorbehalts im Rahmen eines Kreditkaufs ist der Schutz — des Rechtsvorgängers des Verkäufers", options:["Richtig","Falsch"], correct:1},
    {id:190, category:"Allgemeines Vertragsrecht", question:"Verletzt ein Treuhänder seine Pflichten gegenüber dem Treugeben ist auch der Vertrag mit dem Dritten stets unwirksam.", options:["Richtig","Falsch"], correct:1},
    {id:191, category:"Kaufvertrag & Eigentumsübertragung", question:"Wer eine Liegenschaft von bürgerlichem Eigentum kauft, erwirbt im Allgemeinen selbst dann Eigentum an dieser Liegenschaft, wenn der Grundbuchstand falsch sein sollte. Dies nennt man den Grundbuchrechtlichen Vertrauensschutz.", options:["Richtig","Falsch"], correct:0},
    {id:192, category:"Allgemeines Vertragsrecht", question:"Die Fälligkeit der Leistung steht generell im Gesetz.", options:["Richtig","Falsch"], correct:0},
    {id:193, category:"Allgemeines Vertragsrecht", question:"Eine Auslobung ist ein Vertrag", options:["Richtig","Falsch"], correct:1},
    {id:194, category:"Allgemeines Vertragsrecht", question:"Willenserklärungen müssen den Empfänger zugehen?", options:["Richtig","Falsch"], correct:0},
    {id:195, category:"Allgemeines Vertragsrecht", question:"Willenserklärungen sind anhand des Willens des Erklärenden auszulegen?", options:["Richtig","Falsch"], correct:1},
    {id:196, category:"Vertragsabschluss", question:"Bindendes Angebot – A sagt zu B, ich kaufe deinen Fernseher zu einem günstigen Preis und B sagt OK", options:["Richtig","Falsch"], correct:1},
    {id:197, category:"Vertragsabschluss", question:"Ein bindendes Angebot liegt NICHT vor bei Geschwistern?", options:["Richtig","Falsch"], correct:1},
    {id:198, category:"Vertragsabschluss", question:"Ein bindendes Angebot liegt vor bei unaufgeforderten Zusendungen?", options:["Richtig","Falsch"], correct:0},
    {id:199, category:"Stellvertretung & Vollmacht", question:"Ein Stellvertreter muss keinen eigenen Willen bilden.", options:["Richtig","Falsch"], correct:1},
    {id:200, category:"Wurzelmängel & Nichtigkeit", question:"Wurzelmängel können auch nach Vertragsabschluss eintreten.", options:["Richtig","Falsch"], correct:1},
    {id:201, category:"Eigentum & Besitz", question:"Ein gutgläubiger Erwerb ist nach § 367 ABGB bei einer Schenkung möglich.", options:["Richtig","Falsch"], correct:1},
    {id:202, category:"Verzug", question:"Verzugszinsengebühren bei jeder Art von vertraglich geschuldeter Leistung?", options:["Richtig","Falsch"], correct:1},
    {id:203, category:"Verzug", question:"Wenn der Gläubiger trotz Fälligkeit nicht annimmt, spricht man von Leistungsverzug?", options:["Richtig","Falsch"], correct:1},
    {id:204, category:"Forderungsabtretung", question:"Ein Schuldnerwechsel liegt vor bei einer Zession?", options:["Richtig","Falsch"], correct:1},
    {id:205, category:"Allgemeines Vertragsrecht", question:"Ein Schuldnerwechsel liegt vor bei Anerkenntnis?", options:["Richtig","Falsch"], correct:1},
    {id:206, category:"Allgemeines Vertragsrecht", question:"Ein Schuldnerwechsel liegt vor bei einer Schuldänderung?", options:["Richtig","Falsch"], correct:1},
    {id:207, category:"Forderungsabtretung", question:"Ein Schuldnerwechsel liegt vor bei einer Schuldübernahme?", options:["Richtig","Falsch"], correct:0},
    {id:208, category:"Allgemeines Vertragsrecht", question:"Eine verjährte Schuld kann beglichen werden?", options:["Richtig","Falsch"], correct:0},
    {id:209, category:"Allgemeines Vertragsrecht", question:"Ein 15-jähriger darf alleine, d.h. ohne Mitwirkung seiner Eltern, einen Vertrag über einen Ferialjob abschließen.", options:["Richtig","Falsch"], correct:0},
    {id:210, category:"Allgemeines Vertragsrecht", question:"Eine Schenkung ist kein Vertrag, da ja nur der Schenker zu etwas verpflichtet ist.", options:["Richtig","Falsch"], correct:1},
    {id:211, category:"Allgemeines Vertragsrecht", question:"Die sogenannte „Gesellschaft bürgerlichen Rechtes“ gibt seit Einführung des UGB nicht mehr.", options:["Richtig","Falsch"], correct:1},
    {id:212, category:"Wurzelmängel & Nichtigkeit", question:"Dimitri hat Andrea offenbar darüber getäuscht, dass er Russisch kann. Da die Täuschung eines Vertragspartners verboten ist, ist die Vereinbarung gem § 879 ABGB nichtig.", options:["Richtig","Falsch"], correct:1},
    {id:213, category:"Wurzelmängel & Nichtigkeit", question:"Es liegt lediglich schlichte Unmöglichkeit vor, da die Leistung zwar nicht von Dimitri, aber von jemanden anderem vorgenommen werden kann — der Vertrag ist daher gültig.", options:["Richtig","Falsch"], correct:1},
    {id:214, category:"Allgemeines Vertragsrecht", question:"Da Dimitri die Leistung nicht erbringen kann, kann Andrea gem ABGB vorgehen. Sie kann den Vertrag auflösen und muss daher auch nicht €100 an Dimitri zahlen.", options:["Richtig","Falsch"], correct:0},
    {id:215, category:"Wurzelmängel & Nichtigkeit", question:"Sollte Andrea in der Folge die Übersetzungsleistung von jemanden anderem für angemessene €150 erbringen lassen, kann sie Dimitri gem §921 ABGB den Ersatz dieser €150 verlangen.", options:["Richtig","Falsch"], correct:1},
    {id:216, category:"Wurzelmängel & Nichtigkeit", question:"Da Udo doppelt so viel wie den wahren Wert bezahlt hat, kann der den Vertrag wegen laesio enormis (§934 ABGB) anfechten. Mario kann jedoch den Differenzbetrag zahlen, um den Vertrag aufrecht zu erhalten.", options:["Richtig","Falsch"], correct:0},
    {id:217, category:"Wurzelmängel & Nichtigkeit", question:"Da ein auffallendes Missverhältnis von Leistung und Gegenleistung vorliegt, Udo bei Vertragsabschluss in einer Zwangslage war und Mario diesen Umstand ausgenützt hat, kann Udo die Vertragsaufhebung wegen Wuchers begehren (§879 Abs 2 Z 4 ABGB).", options:["Richtig","Falsch"], correct:0},
    {id:218, category:"Irrtum & Täuschung", question:"Da Udo keine Ahnung vom wahren Wert des Ersatzteils hatte, unterlag er einem Wertirrtum, der als Geschäftsirrtum zur Anfechtung gem §871 ABGB berechtigt.", options:["Richtig","Falsch"], correct:1},
    {id:219, category:"Gewährleistung", question:"Da das Ersatzteil einwandfrei funktioniert, ist eine Wandlung gem §932 Abs 4 ABGB ausgeschlossen.", options:["Richtig","Falsch"], correct:0},
    {id:220, category:"Gewährleistung", question:"Da der Preis deutlich höher ist, kann Udo eine Preisminderung gem §932 Abs 4 ABGB begehren.", options:["Richtig","Falsch"], correct:1},
    {id:221, category:"Gewährleistung", question:"Udos Verzweiflung deutet darauf hin, dass er bei Abschluss des Vertrags mit Mario nicht geschäftsfähig war (§865 Abs 1 iVm §24 ABGB), weshalb der Vertrag von Anfang an unwirksam war.", options:["Richtig","Falsch"], correct:1},
    {id:222, category:"Allgemeines Vertragsrecht", question:"Da Udo doppelt so viel wie den wahren Wert des Ersatzteils gezahlt hat, kann er die Lieferung eines zweiten derartigen Teils verlangen.", options:["Richtig","Falsch"], correct:1},
    {id:223, category:"Kaufvertrag & Eigentumsübertragung", question:"Ein Vertrag kommt stets zwischen einem Rechtssubjekt und einem Rechtsobjekt zustande.", options:["Richtig","Falsch"], correct:1},
    {id:224, category:"Verzug", question:"Im vorliegenden Fall ist die Vertragserfüllung während Schuldnerverzug durch Zufall unmöglich geworden", options:["Richtig","Falsch"], correct:0},
    {id:225, category:"Allgemeines Vertragsrecht", question:"Der Vertrag zerfällt von selbst", options:["Richtig","Falsch"], correct:1},
    {id:226, category:"Schadenersatz", question:"Nach Vertragsaufhebung kann Anna einen Schadensersatzanspruch iHv €500 geltend machen (Differenzanspruch).", options:["Richtig","Falsch"], correct:0},
    {id:227, category:"Allgemeines Vertragsrecht", question:"Fritz und Franz können wegen Wegfall der Geschäftsgrundlage (der Umzug wurde abgesagt) die Aufhebung des Balkonplatz-Mietvertrages verlangen.", options:["Richtig","Falsch"], correct:0},
    {id:228, category:"Allgemeines Vertragsrecht", question:"Die richtige Lösung des Falles (Fritz/Franz) ergibt sich aus §871 ABGB.", options:["Richtig","Falsch"], correct:1},
    {id:229, category:"Allgemeines Vertragsrecht", question:"Oma will Enkelin nach bestandener LAP ein Moped verschenken und übergibt ihr, ohne das Ergebnis der LAP zu wissen die Schlüssel. Enkelin besteht jedoch nicht. Darf die Enkelin das Moped trotzdem behalten?", options:["Richtig","Falsch"], correct:1},
    {id:230, category:"Irrtum & Täuschung", question:"Handelt es sich um einen Motivirrtum?", options:["Richtig","Falsch"], correct:0},
    {id:231, category:"Allgemeines Vertragsrecht", question:"Kann die Oma das Moped zurückfordern?", options:["Richtig","Falsch"], correct:0},
    {id:232, category:"Allgemeines Vertragsrecht", question:"Braucht es Einverständnis der Eltern?", options:["Richtig","Falsch"], correct:1},
    {id:233, category:"Wurzelmängel & Nichtigkeit", question:"X kauft von Kunsthändler Statue um € 10.000 vom bekannten Künstler K. nach 4 Jahren will er die Statue verkaufen und kommt drauf, dass sie nicht von K ist nur € 500 Wert ist. Kann wegen Wucher klagen", options:["Richtig","Falsch"], correct:1},
    {id:234, category:"Gewährleistung", question:"X kann wegen Gewährleistung oder Irrtum klagen (Kunsthändler-Fall).", options:["Richtig","Falsch"], correct:1},
    {id:235, category:"Allgemeines Vertragsrecht", question:"X kann wegen List klagen (Kunsthändler-Fall).", options:["Richtig","Falsch"], correct:0},
    {id:236, category:"Schadenersatz", question:"Der Student S fährt mit dem GVB –Bus zur Uni und kauft sich beim Einsteigen ein Ticket beim Automaten. Er setzt sich auf einen Sitz, der nicht vom Fahrer geprüft wurde. Während der Fahrt bricht der Sitz hinunter und S verletzt sich dabei. Er verlangt Schmerzensgeld von der GVB, jedoch die weigert sich vehement, weil sie direkt neben dem Ticketautomaten die AGB aufgehängt haben und die eine FETT gedruckte Klausel beinhaltet, in der eine Haftung ausgeschlossen wird. S sagt, dass er die Klausel nicht gesehen hat und so ein Haftungsausschluss sowieso nicht möglich ist. Ist dieser Haftungsausschluss gültig und muss die GVB-Schadenersatz zahlen?", options:["Richtig","Falsch"], correct:1},
    {id:237, category:"Allgemeines Vertragsrecht", question:"Am Dienstag um 13 Uhr ist ein Vertrag zwischen V und K geschlossen worden.", options:["Richtig","Falsch"], correct:0},
    {id:238, category:"Allgemeines Vertragsrecht", question:"Es gibt einen gültigen Vertrag zwischen V und N", options:["Richtig","Falsch"], correct:1},
    {id:239, category:"Allgemeines Vertragsrecht", question:"Am Dienstag um 18 Uhr wird K Eigentümer des PC", options:["Richtig","Falsch"], correct:1},
    {id:240, category:"Allgemeines Vertragsrecht", question:"V ist noch Eigentümer des PC", options:["Richtig","Falsch"], correct:0}
  ]
});
