/* ============================================================
 *  Einführung in die Soziologie – Altfragen (Reicher 2024/25)
 * ============================================================ */

SUBJECTS.push({
  name: "Einführung in die Soziologie",
  icon: "🏛️",
  description: "Altfragen aus der VO Einführung in die Soziologie (Reicher 2024/25).",

  kk: [
    {id:1, category:"Altfragen", question:"Nenne die Basisemotionen laut Ekman?", answer:"Freude, Wut, Ekel, Trauer, Verachtung und Überraschung"},
    {id:2, category:"Altfragen", question:"Welche vier modernen Gesellschaftstypen gibt es und nenne jeweils ein Beispiel?", answer:"o Erste Welt (Westen): Industrieländer mit hohem Lebensstandard.\no Zweite Welt: Ehemalige sozialistische Ländern zb. Sowjetunion\no Dritte Welt: Weniger entwickelte Ländern, oft kolonialistisch geprägt\no Schwellenländern und BRICS-Staaten: Länder, die sich wirtschaftlich entwickeln"},
    {id:3, category:"Altfragen", question:"Erkläre die drei Phasen der demographischen Gesellschaftsentwicklung.", answer:"18. und 19 Jhdt. Begannen die Sterberaten zu sinken\nHälfte des 20. Jhdt. Sanken die Geburtsraten\nAb Hälfte des 20. Jhdt. Stellte sich wieder demographischen Gleichgewicht ein"},
    {id:4, category:"Altfragen", question:"Nenne zwei Formen von Unter- und Überordnung in sozialer Ordnung?", answer:"Machtstrukturen und Statusbeziehungen"},
    {id:5, category:"Altfragen", question:"Definiere den Begriff Subsistenzwirtschaft.", answer:"Subsistenzwirtschaft ist eine Wirtschaftsform, in der die Produktion überwiegend für den\nEigenbedarf erfolgt. Ziel ist nicht der Verkauf am Markt, sondern die Sicherung des\neigenen Lebensunterhalts."},
    {id:6, category:"Altfragen", question:"Definiere den Begriff Tauschwirtschaft.", answer:"Tauschwirtschaft ist eine Wirtschaftsform, in der Güter oder Dienstleistungen direkt\ngegen andere eingetauscht werden, ohne den Einsatz von Geld. Dabei bleibt jede Einheit\nweitgehend autark, da sie produziert, was sie braucht, und nur das\ndarüberhinausgehende gegen andere Güter tauscht."},
    {id:7, category:"Altfragen", question:"Seit wie vielen Jahren gibt es den Homo Sapiens?", answer:"300.000-150.000 Jahren"},
    {id:8, category:"Altfragen", question:"Nenne die Entwicklungsphasen nach Freud und deren zeitlichen Rahmen.", answer:"o Orale Phase (bis 2 Jahre) – Lust durch Saugen und Nahrungsaufnahme.\no Anale Phase (2–3 Jahre) – Kontrolle über Ausscheidungen.\no Phallische Phase (3–5 Jahre) – Ödipuskomplex, Identifikation mit Eltern.\no Latenzperiode (5–11 Jahre) – Sexualität tritt zurück, Fokus auf kognitive Entwicklung.\no Genitale Phase (ab 12 Jahre) – Erwachen der Sexualität in sozialer Interaktion"},
    {id:9, category:"Altfragen", question:"Was sind die drei Hauptwirtschaftsformen?", answer:"Tauschwirtschaft, Planwirtschaft und Marktwirtschaft"},
    {id:10, category:"Altfragen", question:"Was sind zwei Charaktertypen der Elite nach Pareto?", answer:"Löwe: starke Machthaber und Füchse: schlaue Manipulatoren"},
    {id:11, category:"Altfragen", question:"Was sind die Klassen nach dem EGP-Modell und nenne jeweils ein Beispiel.", answer:"Erfolgt über Unterscheidung nach Berufspositionen:\n1. Dienstklasse (z. B. Manager, Beamte, Firmeninhaber)\n2. Mittelklasse (Angestellte mit Routinearbeiten, Verkäufer)\n3. Arbeiterklasse (Vorarbeiter, Facharbeiter, ungelernte Arbeiter)"},
    {id:12, category:"Altfragen", question:"Nenne Webers vier Handlungstypen und beschreibe diese.", answer:"o Zweckrationales Handeln: Rationales Abwägen von Optionen.\no Wertrationales Handeln: Handeln basierend auf ethischen Werten.\no Affektives Handeln: Emotion gesteuertes Handeln.\no Traditionelles Handeln: Handeln aufgrund von Gewohnheiten."},
    {id:13, category:"Altfragen", question:"Nenne vier Eigenschaften für Kapitalismus.", answer:"Freie Marktwirtschaft, Monopolisierung, Privateigentum, Gewinnorientierung"},
    {id:14, category:"Altfragen", question:"Was sind vier vormoderne Gesellschaftstypen und nenne jeweils ein Beispiel.", answer:"Jäger- und Sammlergesellschaften z B. Die San\nAgrargesellschaften z B. die Krobo\nWeidelandgesellschaften z B. Die Tuareg\nHochkulturen oder klassische Zivilisationen z B. Königreich der Abessinien"},
    {id:15, category:"Altfragen", question:"Definiere den Begriff Nation laut Meinecke.", answer:"Kulturnation und Staatsnation"},
    {id:16, category:"Altfragen", question:"Was ist „mala in se“ und „mala prohibita“?", answer:"Thomas von Aquin unterschied zwischen mala in se, der moralisch schlechten Taten und\nmala prohibita, Tat en die gegen das Gesetz verstoßen. Diese Unterscheidung wurde in\ncommon low also in das englische Gewohnheitsrecht aufgenommen."},
    {id:17, category:"Altfragen", question:"Nenne die vier Arten der Arbeitslosigkeit und beschreibe diese.", answer:"1. Strukturelle Arbeitslosigkeit:\n▪ Betrifft bestimmte soziale Gruppen (gering qualifizierte, ältere Menschen,\nMinderheiten).\n2. Friktionelle Arbeitslosigkeit:\n▪ Übergangsarbeitslosigkeit bei Jobwechseln (freiwillig/unfreiwillig)\nIn seinem Skript werden zwar nur die zwei genannt aber sonst zusätzlich:\n3. Konjunkturelle Arbeitslosigkeit:\n▪ Aufgrund schwankender Wirtschaftslage\n4. Saisonelle Arbeitslosigkeit:\n▪ jahreszeitlich bedingt"},
    {id:18, category:"Altfragen", question:"In welchem Jahr fand die Französische Revolution statt?", answer:"1789"},
    {id:19, category:"Altfragen", question:"Welche Arten von Nationen gibt es laut Kohn?", answer:"Bürgernation und Ethno-Nation"},
    {id:20, category:"Altfragen", question:"Welche Probleme können bei der Messung von Kriminalität auftreten?", answer:"• Objektivitätsproblem\no Nicht alle Straftaten werden registriert\no Polizeiliche Stereotype beeinflussen Erfassung (z. B. Fokus auf bestimmte\nGruppen/Milieus)\n• Validitätsproblem\no Definition von Straftaten verändert sich historisch und kulturell\no Beispiel: Homosexualität früher strafbar, Mobbing heute relevant\n• Hellfeld vs. Dunkelfeld\no Hellfeld: offiziell registrierte Straftaten\no Dunkelfeld: nicht gemeldete/entdeckte Taten → wahre Kriminalitätsrate höher\no Dunkelfeld nur schätzbar (z. B. Dunkelfeldstudien)\n• Einflussfaktoren auf Statistik\no Anzeigeverhalten der Bevölkerung\no Polizeiliche Präsenz und Ermittlungsmethoden\no Unterschiedliche Dunkelfelder je nach Delikt (z. B. Mord vs. Diebstahl)"},
    {id:21, category:"Altfragen", question:"Nenne Giddens‘ drei Akteurs Ebenen.", answer:"1. Diskursives Bewusstsein – Bewusstes Nachdenken über soziale Regeln und deren\nAnwendung (hoher Grad an Reflexion).\n2. Praktisches Bewusstsein – Handlungen werden ausgeführt, ohne über Regeln\nnachzudenken, was Routinen und Konventionen erzeugt.\n3. Unterbewusstsein – Unbewusste Motive des Handelns, die für die Akteure selbst nicht\nzugänglich sind."},
    {id:22, category:"Altfragen", question:"In welchem Jahrhundert fand die Industrialisierung statt?", answer:"18. Jhdt. Circa 1750"},
    {id:23, category:"Altfragen", question:"In welchem Jahr die Globalisierung statt?", answer:"20 Jhdt. Circa ab 1990"},
    {id:24, category:"Altfragen", question:"Nenne die zwei relevanten Gefühle nach Scheff?", answer:"Stolz und Scham"},
    {id:25, category:"Altfragen", question:"Nenne drei Arten vormoderner sozialer Schichten?", answer:"Sklaverei, Kastenwesen und Ständewesen"},
    {id:26, category:"Altfragen", question:"Nenne Verteilungen individueller Merkmale.", answer:"Alter, Geschlecht, Familienstand, Bildung, Einkommen, Religion, Muttersprache"},
    {id:27, category:"Altfragen", question:"Erkläre den Begriff „Moralische Panik“.", answer:"Überreaktion durch Massenmedien auf ein negativ empfundenes Ereignis"},
    {id:28, category:"Altfragen", question:"Was sind Verteilungsmuster von sozialen Strukturen?", answer:"(keine Antwort im PDF)"},
    {id:29, category:"Altfragen", question:"Was sind zwei Arten von Ritualen?", answer:"Zeremonielle Rituale (Religiöse Rituale) und Alltagsrituale (Begrüßungen)"},
    {id:30, category:"Altfragen", question:"Was sind zwei Formen von Armut?", answer:"1. Absolute Armut:\n▪ Leben am Existenzminimum\n▪ Grundbedürfnisse nicht mehr bezahlbar\n▪ Gefahr von Obdachlosigkeit\n2. Relative Armut:\n▪ Abstand zum durchschnittlichen Wohlstandsniveau\n▪ Armutsgrenze in Österreich: 60 % des Medianeinkommens"},
    {id:31, category:"Altfragen", question:"Was versteht man unter horizontaler und vertikaler Mobilität?", answer:"o Horizontal: Wechsel innerhalb derselben Statusgruppe\no Vertikal: Auf. Oder Abstieg im sozialen Raum"},
    {id:32, category:"Altfragen", question:"Definiere Inter- und Intragenerationenmobilität.", answer:"o Intergenerationenmobilität:\n▪ Vergleich der sozialen Position zwischen Generationen (z. B. Kinder haben höhere\nBerufe als Eltern)\no Intragenerationenmobilität:\n▪ Statusveränderung innerhalb eines individuellen Lebensverlaufs"},
    {id:33, category:"Altfragen", question:"Definiere Taylorismus, Toyotismus und Fordismus.", answer:"o Taylorismus: wissenschaftliche Arbeitszerlegung, einzelne standardisierte\nArbeitsschritte, spezialisierte Arbeitskräfte\no Fordismus: Fließbandarbeit, Massenprduktion, hohe Stückzahlen\no Toyotismus: flexible Produktion, Just-in-time-Prinzip, geringe Lagerhaltung"},
    {id:34, category:"Altfragen", question:"Wie kann Arbeitslosigkeit gemessen werden?", answer:"o Zählung durch Arbeitsämter (AMS in Österreich)\no Erhebung durch Umfragen (Surveystudien)"},
    {id:35, category:"Altfragen", question:"Was sind Probleme bei der Messung der Arbeitslosigkeit?", answer:"o Arbeitslosenzahlen hängen von Definition & Erfassungsmethoden ab.\no Arbeitslose, die sich nicht beim Arbeitsamt melden, werden nicht erfasst.\no Schwarzarbeit & unbezahlte Tätigkeiten werden nicht berücksichtigt"},
    {id:36, category:"Altfragen", question:"Was sind zwei Theorien, die soziale Schichten erklären?", answer:"Funktionalismus und Überlagerungstheorie"},
    {id:37, category:"Altfragen", question:"Nenne die zwei Lerntheorien und erkläre diese.", answer:"1. Behaviorismus (Lernen als passive Reaktion auf Reize):\no Menschliches Gehirn wird als „Black Box“ gesehen.\no Lernen geschieht durch äußere Reize und Konditionierung.\nIwan Pawlow: Klassische Konditionierung (z. B. Pawlowscher Hund).\nJohn B. Watson: Übertragung klassischen Konditionierung auf Menschen.\nBurrhus F . Skinner: Operante Konditionierung – Verhalten wird durch Belohnung\noder Bestrafung geformt.\n2. Lernen als aktiver Vorgang:\no Menschen sind keine passiven Empfänger, sondern lernen aktiv.\no Implizites Lernen: Erwerb von Wissen durch tägliche Praxis („learning by doing“), führt\nzu Routinen undautomatischen Verhaltensweisen.\no Explizites Lernen: Bewusstes Reflektieren und Verbalisieren von Wissen"},
    {id:38, category:"Altfragen", question:"Erkläre die zwei Arten von Solidarität.", answer:"Nach Emile Durkheim:\n▪ Mechanische Solidarität: In einfachen Gesellschaften, basiert auf Ähnlichkeit &\nTradition.\n▪ Organische Solidarität: In hoch arbeitsteiligen Gesellschaften, basiert auf Abhängigkeit\n& Kooperation"},
    {id:39, category:"Altfragen", question:"Was waren vorherrschende politische Ideologien im 19 Jhdt.?", answer:"Liberalismus, Konservatismus und Sozialismus"},
    {id:40, category:"Altfragen", question:"Nenne die Entwicklungsphasen nach Piaget.", answer:"o Sensomotorisches Stadium (bis 2 Jahre) – Entwicklung von Wahrnehmung und\nObjektpermanenz.\no Prä-operationales Stadium (2–7 Jahre) – Sprache, Egozentrismus, kindliche\nVorstellungen (Animismus, Realismus).\no Konkrete operationale Phase (7–11 Jahre) – Logisches Denken über konkrete Dinge.\no Formale operationale Phase (11–15 Jahre) – Hypothetisches und abstraktes Denken"},
    {id:41, category:"Altfragen", question:"Nenne die zwei unterschiedlichen Auffassungen von Sozialstruktur.", answer:"1. Äußere Verteilung individueller Merkmale: (z B. Normalverteilung)\no Statistisch beobachtbar\no Statistische Verteilungsmuster wurden im 19. Jahrhundert entdeckt, u. a. die\nNormalverteilung von Adolph Quetelet\no Soziodemographische Merkmale: Alter, Geschlecht, Familienstand, Bildung,\nReligion,…\no Verteilungsmuster und Durchschnittswerte\n2. Inhärente Beziehungsregeln: (z B. soziale Ungleichheit)\no Regeln innerhalb sozialer Beziehungen\no Beziehungsmuster\no Kollektive und relationale Merkmale"},
    {id:42, category:"Altfragen", question:"Staatenbildung", answer:"• Früheste Staatenbildung: Erste Hochkulturen, Städte, Schrift, soziale Ungleichheit,\nEliten monopolisierten Ressourcen, Kriegsführung zur Machtabsicherung\n• Frühere Staaten als \"Kriegsmaschinen\": Gewalt zur Kontrolle und Finanzierung von\nKriegen\n• Entwicklung von Stadtstaaten und Großreichen: griechische Polis, römisches\nImperium, Großreiche (Babylonier, Perser)\n• Mittelalterliche Staatsentwicklung: Feudalismus, später Zentralisierung (z. B.\nFrankreich, Preußen)\n• Entstehung der Nationalstaaten (18.–19. Jh.): Nationalstaaten, erweiterte\nPartizipation, Volksarmeen, Sozialpolitik\n• Wirtschaftspolitische Veränderungen & europäische Integration (ab 1945):\nStaatliche Wirtschaftseingriffe, europäische Integration (EU, NATO)"}
  ],

  mc: []
});
